# Generated by Django 5.1.4 on 2026-07-22 14:41

import apps.orders.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cart_preferred_warehouse_and_more"),
        ("catalog", "0003_alter_artisan_region_and_more"),
        ("inventory", "0003_alter_inventory_damaged_quantity_and_more"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="couponusage",
            name="coupon_usage_discount_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="discountline",
            name="discountline_amount_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="discountline",
            name="discountline_base_amount_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="refund",
            name="refund_amount_gt_0",
        ),
        migrations.RemoveConstraint(
            model_name="returnitem",
            name="returnitem_quantity_returned_gt_0",
        ),
        migrations.RemoveConstraint(
            model_name="returnitem",
            name="returnitem_qty_received_lte_returned",
        ),
        migrations.RemoveConstraint(
            model_name="taxline",
            name="taxline_base_amount_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="taxline",
            name="taxline_tax_amount_gte_0",
        ),
        migrations.RemoveIndex(
            model_name="couponusage",
            name="orders_coup_user_id_f8eb7b_idx",
        ),
        migrations.RemoveIndex(
            model_name="couponusage",
            name="orders_coup_order_i_ee4ca0_idx",
        ),
        migrations.RemoveIndex(
            model_name="couponusage",
            name="orders_coup_coupon__951311_idx",
        ),
        migrations.RemoveIndex(
            model_name="couponusage",
            name="orders_coup_is_reve_99cdb0_idx",
        ),
        migrations.RemoveIndex(
            model_name="couponusage",
            name="orders_coup_cart_id_0f6617_idx",
        ),
        migrations.RemoveIndex(
            model_name="discountline",
            name="orders_disc_order_i_c65ead_idx",
        ),
        migrations.RemoveIndex(
            model_name="discountline",
            name="orders_disc_discoun_e6f6ca_idx",
        ),
        migrations.RemoveIndex(
            model_name="discountline",
            name="orders_disc_coupon__47dcdd_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderattachment",
            name="orders_orde_order_i_b6e99a_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderattachment",
            name="orders_orde_attachm_5b6688_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderattachment",
            name="orders_orde_is_acti_e8a061_idx",
        ),
        migrations.RemoveIndex(
            model_name="ordernote",
            name="orders_orde_order_i_e9cb48_idx",
        ),
        migrations.RemoveIndex(
            model_name="ordernote",
            name="orders_orde_order_i_348b6e_idx",
        ),
        migrations.RemoveIndex(
            model_name="ordernote",
            name="orders_orde_author__a3764c_idx",
        ),
        migrations.RemoveIndex(
            model_name="ordertimelineevent",
            name="orders_orde_order_i_f4dff6_idx",
        ),
        migrations.RemoveIndex(
            model_name="ordertimelineevent",
            name="orders_orde_event_t_acd1fd_idx",
        ),
        migrations.RemoveIndex(
            model_name="ordertimelineevent",
            name="orders_orde_order_i_65a20c_idx",
        ),
        migrations.RemoveIndex(
            model_name="ordertimelineevent",
            name="orders_orde_referen_0a11c6_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="orders_paym_order_i_ee6c4b_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="orders_paym_status_5b2895_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="orders_paym_gateway_c09238_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="orders_paym_payment_753274_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymentattempt",
            name="orders_paym_payment_fdef67_idx",
        ),
        migrations.RemoveIndex(
            model_name="refund",
            name="orders_refu_order_i_42a972_idx",
        ),
        migrations.RemoveIndex(
            model_name="refund",
            name="orders_refu_payment_249703_idx",
        ),
        migrations.RemoveIndex(
            model_name="refund",
            name="orders_refu_status_0afff0_idx",
        ),
        migrations.RemoveIndex(
            model_name="refund",
            name="orders_refu_refund__440bff_idx",
        ),
        migrations.RemoveIndex(
            model_name="returnimage",
            name="orders_retu_return__9542c6_idx",
        ),
        migrations.RemoveIndex(
            model_name="returnitem",
            name="orders_retu_return__d5ab93_idx",
        ),
        migrations.RemoveIndex(
            model_name="returnitem",
            name="orders_retu_order_i_6f73a4_idx",
        ),
        migrations.RemoveIndex(
            model_name="returnrequest",
            name="orders_retu_order_i_bab601_idx",
        ),
        migrations.RemoveIndex(
            model_name="returnrequest",
            name="orders_retu_status_3b5dcd_idx",
        ),
        migrations.RemoveIndex(
            model_name="returnrequest",
            name="orders_retu_return__4d0761_idx",
        ),
        migrations.RemoveIndex(
            model_name="returnrequest",
            name="orders_retu_reason__ac0f05_idx",
        ),
        migrations.RemoveIndex(
            model_name="returnrequest",
            name="orders_retu_request_ed53f3_idx",
        ),
        migrations.RemoveIndex(
            model_name="returnrequest",
            name="orders_retu_refund__d15019_idx",
        ),
        migrations.RemoveIndex(
            model_name="returnrequest",
            name="orders_retu_replace_bbebc8_idx",
        ),
        migrations.RemoveIndex(
            model_name="shipmentitem",
            name="orders_ship_shipmen_125d16_idx",
        ),
        migrations.RemoveIndex(
            model_name="shipmentitem",
            name="orders_ship_order_i_573d0b_idx",
        ),
        migrations.RemoveIndex(
            model_name="taxline",
            name="orders_taxl_order_i_a8927e_idx",
        ),
        migrations.RemoveIndex(
            model_name="taxline",
            name="orders_taxl_tax_cla_6ca8ca_idx",
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="cart_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupon_usages",
                to="cart.cart",
            ),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="category_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupon_usages",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="coupon_code",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="is_reversed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_usages",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="product_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupon_usages",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="reversal_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="reversed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="couponusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="applies_to_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_lines",
                to="orders.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="base_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="code",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="coupon_usage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_lines",
                to="orders.couponusage",
            ),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("coupon", "Coupon Code"),
                    ("promotion", "Promotion"),
                    ("loyalty", "Loyalty Reward"),
                    ("staff", "Staff Adjustment"),
                    ("goodwill", "Goodwill"),
                    ("bulk", "Bulk Discount"),
                    ("seasonal", "Seasonal Discount"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="is_stackable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="is_taxable",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_lines",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="promotion_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="discountline",
            name="source",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="order",
            name="abandoned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="abandoned_recovery_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="base_currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="base_currency_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="orders.orderaddresssnapshot",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="carrier",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(default="NPR", max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency_symbol",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_locale",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_timezone",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Order Email"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("1.00000000"),
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("1E-8"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="expected_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="external_order_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=120, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="external_platform",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="fraud_check_status",
            field=models.CharField(
                choices=[
                    ("not_checked", "Not Checked"),
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("manual_review", "Under Manual Review"),
                ],
                db_index=True,
                default="not_checked",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="gift_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="gift_wrapping",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="has_invoice",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="invoice_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_gift",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="json_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially Refunded"),
                    ("authorized", "Authorized"),
                    ("captured", "Captured"),
                    ("voided", "Voided"),
                    ("disputed", "Disputed"),
                    ("expired", "Expired"),
                    ("pending_payment", "Pending Payment"),
                    ("processing", "Processing"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="personalization_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="order",
            name="referrer_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="risk_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="orders.orderaddresssnapshot",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="source",
            field=models.CharField(
                choices=[
                    ("web", "Web Storefront"),
                    ("admin", "Admin / Staff"),
                    ("api", "API"),
                    ("import", "Bulk Import"),
                    ("phone", "Phone Order"),
                    ("marketplace", "Marketplace"),
                    ("subscription", "Subscription Renewal"),
                    ("pos", "Point of Sale"),
                    ("migration", "Data Migration"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="web",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                    ("on_hold", "On Hold"),
                    ("partially_shipped", "Partially Shipped"),
                    ("partially_delivered", "Partially Delivered"),
                    ("backordered", "Backordered"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("awaiting_payment", "Awaiting Payment"),
                    ("partially_refunded", "Partially Refunded"),
                    ("disputed", "Disputed"),
                    ("draft", "Draft"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="order",
            name="tags_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="orderaddresssnapshot",
            name="address_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="orderaddresssnapshot",
            name="country_code",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="ISO Country Code"
            ),
        ),
        migrations.AlterField(
            model_name="orderaddresssnapshot",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderaddresssnapshot",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderaddresssnapshot",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="orderaddresssnapshot",
            name="phone_e164",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Phone (E.164)"
            ),
        ),
        migrations.AlterField(
            model_name="orderattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice PDF"),
                    ("packing_slip", "Packing Slip"),
                    ("delivery_proof", "Delivery Proof"),
                    ("customs", "Customs Declaration"),
                    ("insurance", "Insurance Certificate"),
                    ("customer_doc", "Customer Document"),
                    ("operator_doc", "Operator Document"),
                    ("return_label", "Return Label"),
                    ("replacement_label", "Replacement Label"),
                    ("signature", "Signed Delivery Proof"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="orderattachment",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderattachment",
            name="file",
            field=models.FileField(
                upload_to=apps.orders.models._order_attachment_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="orderattachment",
            name="file_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderattachment",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="orderattachment",
            name="is_visible_to_customer",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="orderattachment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="orderattachment",
            name="mime_type",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="orderattachment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderattachment",
            name="original_filename",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="orderattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="added_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="expected_ship_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="gift_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="gift_wrapping",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="inventory.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="inventory_reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="inventory.stockreservation",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="is_gift",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="personalization",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_item_product_set",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_brand_snapshot",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_image_snapshot_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_meta_description_snapshot",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_meta_title_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_origin_snapshot",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_sku_snapshot",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_slug_snapshot",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="promised_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity_refunded",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity_returned",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity_shipped",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="saved_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manually Saved"),
                    ("replaced", "Replaced By Newer Variant"),
                    ("out_of_stock", "Variant Out Of Stock"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("saved", "Saved For Later"),
                    ("removed", "Removed"),
                    ("expired", "Expired"),
                    ("returned", "Returned"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                    ("partially_returned", "Partially Returned"),
                    ("partially_shipped", "Partially Shipped"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="supplier_name_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="supplier_order_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="tax",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_item_variant_set",
                to="catalog.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant_barcode_snapshot",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant_image_snapshot_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant_name_snapshot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant_sku_snapshot",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant_weight_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.000"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="inventory.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="warehouse_code_snapshot",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="warehouse_name_snapshot",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="weight",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.000"))],
            ),
        ),
        migrations.AlterField(
            model_name="ordernote",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ordernote",
            name="is_pinned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="ordernote",
            name="is_visible_to_customer",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="ordernote",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="ordernote",
            name="note_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer Note"),
                    ("operator", "Internal Operator Note"),
                    ("gift", "Gift Message"),
                    ("delivery", "Delivery Instructions"),
                    ("system", "System-Generated Note"),
                ],
                db_index=True,
                default="operator",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="ordernote",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_notes",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="ordernote",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="is_customer_notified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="new_status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="notification_method",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="old_status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ordertimelineevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ordertimelineevent",
            name="color",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="ordertimelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("order_placed", "Order Placed"),
                    ("order_updated", "Order Updated"),
                    ("order_cancelled", "Order Cancelled"),
                    ("order_completed", "Order Completed"),
                    ("payment_initiated", "Payment Initiated"),
                    ("payment_authorized", "Payment Authorized"),
                    ("payment_captured", "Payment Captured"),
                    ("payment_failed", "Payment Failed"),
                    ("payment_refunded", "Payment Refunded"),
                    ("shipment_created", "Shipment Created"),
                    ("shipment_picked", "Shipment Picked Up"),
                    ("shipment_in_transit", "Shipment In Transit"),
                    ("shipment_out_for_delivery", "Out for Delivery"),
                    ("shipment_delivered", "Shipment Delivered"),
                    ("shipment_failed", "Shipment Failed"),
                    ("shipment_returned", "Shipment Returned"),
                    ("refund_initiated", "Refund Initiated"),
                    ("refund_approved", "Refund Approved"),
                    ("refund_rejected", "Refund Rejected"),
                    ("refund_completed", "Refund Completed"),
                    ("note_added", "Note Added"),
                    ("attachment_added", "Attachment Added"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("return_rejected", "Return Rejected"),
                    ("return_received", "Return Received"),
                    ("return_completed", "Return Completed"),
                    ("discount_applied", "Discount Applied"),
                    ("discount_reversed", "Discount Reversed"),
                    ("fraud_check_passed", "Fraud Check Passed"),
                    ("fraud_check_failed", "Fraud Check Failed"),
                    ("fraud_check_review", "Fraud Check Under Review"),
                    ("inventory_allocated", "Inventory Allocated"),
                    ("inventory_deducted", "Inventory Deducted"),
                    ("inventory_restocked", "Inventory Restocked"),
                    ("inventory_transferred", "Inventory Transferred"),
                    ("system", "System Event"),
                ],
                db_index=True,
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="ordertimelineevent",
            name="icon",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ordertimelineevent",
            name="is_system_event",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="ordertimelineevent",
            name="is_visible_to_customer",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="ordertimelineevent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="ordertimelineevent",
            name="occurred_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="ordertimelineevent",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="ordertimelineevent",
            name="reference_id",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="ordertimelineevent",
            name="reference_model",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="ordertimelineevent",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="NPR", max_length=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="gateway_response_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="payment",
            name="is_test_payment",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_attempts_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="risk_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("authorized", "Authorized"),
                    ("captured", "Captured"),
                    ("partially_refunded", "Partially Refunded"),
                    ("voided", "Voided"),
                    ("expired", "Expired"),
                    ("disputed", "Disputed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="attempted_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="gateway_response_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="gateway_response_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="gateway_response_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="orders.payment",
            ),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failure", "Failure"),
                    ("timeout", "Timeout"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="evidence_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="refund",
            name="gateway_refund_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="refund",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="refund",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refunds",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="orders.payment",
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="reason",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="refund",
            name="refund_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("original", "Original Payment Method"),
                    ("store_credit", "Store Credit"),
                    ("bank_transfer", "Bank Transfer"),
                    ("check", "Check"),
                    ("cash", "Cash"),
                    ("other", "Other"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="refund_reason_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer_request", "Customer Request"),
                    ("defective_product", "Defective Product"),
                    ("wrong_item", "Wrong Item Shipped"),
                    ("not_as_described", "Not as Described"),
                    ("duplicate_charge", "Duplicate Charge"),
                    ("fraud", "Fraudulent Transaction"),
                    ("goodwill", "Goodwill Gesture"),
                    ("other", "Other"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("processed", "Processed"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending Gateway"),
                    ("failed", "Gateway Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="requested",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="returnimage",
            name="caption",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="returnimage",
            name="image",
            field=models.ImageField(
                upload_to=apps.orders.models._return_image_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="returnimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("evidence", "Evidence"),
                    ("reference", "Reference"),
                    ("packaging", "Packaging"),
                    ("label", "Label"),
                    ("operator", "Operator"),
                    ("other", "Other"),
                ],
                default="evidence",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="returnimage",
            name="return_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="orders.returnitem",
            ),
        ),
        migrations.AlterField(
            model_name="returnimage",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="condition_received",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="inspection_result",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Inspection"),
                    ("passed", "Passed Inspection"),
                    ("failed", "Failed Inspection"),
                    ("partial", "Partial Pass"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_items",
                to="orders.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="quantity_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="quantity_received",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="quantity_returned",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="refund_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="replacement_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replacement_for",
                to="orders.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="restock_decision",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="return_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.returnrequest",
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_requests_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_requests",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="reason_category",
            field=models.CharField(
                choices=[
                    ("defective", "Defective / Damaged"),
                    ("wrong_item", "Wrong Item Shipped"),
                    ("not_as_described", "Not as Described"),
                    ("size_issue", "Size or Fit Issue"),
                    ("color_issue", "Color Discrepancy"),
                    ("quality_issue", "Quality Issue"),
                    ("damaged_in_transit", "Damaged in Transit"),
                    ("late_delivery", "Late Delivery"),
                    ("changed_mind", "Changed Mind"),
                    ("duplicate_order", "Duplicate Order"),
                    ("better_price_found", "Better Price Found"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="refund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_requests",
                to="orders.refund",
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_requests_rejected",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="replacement_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replacement_return_requests",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_requests_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="restock_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("restock", "Restock"),
                    ("dispose", "Dispose"),
                    ("return_to_supplier", "Return to Supplier"),
                    ("repair", "Repair"),
                    ("quarantine", "Quarantine"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="restock_location",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="return_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="return_shipping_address_snapshot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_request",
                to="orders.orderaddresssnapshot",
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="return_type",
            field=models.CharField(
                choices=[
                    ("refund", "Refund"),
                    ("replacement", "Replacement"),
                    ("exchange", "Exchange"),
                    ("store_credit", "Store Credit"),
                    ("repair", "Repair"),
                ],
                default="refund",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("requested", "Requested"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("awaiting_shipment", "Awaiting Return Shipment"),
                    ("in_transit", "Return In Transit"),
                    ("received", "Received"),
                    ("inspecting", "Inspecting"),
                    ("refund_initiated", "Refund Initiated"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="carrier",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="carrier_api_integration_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="carrier_service_level",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="dimensions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipment_number",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipping_cost_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dispatched", "Dispatched"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("returned", "Returned"),
                    ("exception", "Exception"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("failed_attempt", "Failed Delivery Attempt"),
                    ("awaiting_pickup", "Awaiting Pickup"),
                    ("picked_up", "Picked Up"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="total_weight",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.000"))],
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="tracking_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="tracking_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="inventory.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="condition_at_pickup",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="is_replacement",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment_line_items",
                to="orders.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="quantity_shipped",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="replaced_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replacements",
                to="orders.shipmentitem",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="serial_tracking",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="serial_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="orders.shipment",
            ),
        ),
        migrations.AlterField(
            model_name="taxline",
            name="base_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="taxline",
            name="is_inclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="taxline",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="taxline",
            name="mode",
            field=models.CharField(
                choices=[("inclusive", "Inclusive"), ("exclusive", "Exclusive")],
                default="exclusive",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="taxline",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_lines",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="taxline",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="taxline",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="taxline",
            name="tax_authority_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="taxline",
            name="tax_class",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="taxline",
            name="tax_name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="taxline",
            name="tax_rate",
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
