# Generated by Django 5.1.4 on 2026-06-29 14:07

import apps.customers.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_collection_productcollection_productgalleryimage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Primary contact number for order fulfillment and notifications.",
                        max_length=32,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Customer profile portrait photograph.",
                        null=True,
                        upload_to=apps.customers.models.customer_avatar_upload_path,
                        verbose_name="Avatar Image",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Used for age verification and personalized marketing offers.",
                        null=True,
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                            ("PREFER_NOT_TO_SAY", "Prefer Not To Say"),
                        ],
                        max_length=24,
                        null=True,
                        verbose_name="Gender Profile",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="en",
                        help_text="ISO language code for localized messaging and emails.",
                        max_length=16,
                        null=True,
                        verbose_name="Preferred Language",
                    ),
                ),
                (
                    "newsletter_subscribed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the customer opted into marketing email distributions.",
                        verbose_name="Newsletter Subscribed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Reference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Profile",
                "verbose_name_plural": "Customer Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Recipient full name for delivery/billing identification.",
                        max_length=255,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Specific delivery point contact telephone number.",
                        max_length=50,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(max_length=255, verbose_name="Address Line 1"),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Address Line 2",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "state_or_province",
                    models.CharField(max_length=100, verbose_name="State or Province"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Postal Code"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("BILLING", "Billing"),
                            ("SHIPPING", "Shipping"),
                            ("BOTH", "Both"),
                        ],
                        default="BOTH",
                        max_length=20,
                        verbose_name="Address Type",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Designates this node as the primary automatic address selector.",
                        verbose_name="Is Default Address",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft delete indicator to protect transactional integrity across past orders.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customerprofile",
                        verbose_name="Customer Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Address",
                "verbose_name_plural": "Customer Addresses",
                "ordering": ["-is_default", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A custom identifiable or auto-assigned name for this persistent cart instance.",
                        max_length=150,
                        verbose_name="Cart Name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_carts",
                        to="customers.customerprofile",
                        verbose_name="Customer Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Cart",
                "verbose_name_plural": "Saved Carts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_cart_items",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "saved_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="customers.savedcart",
                        verbose_name="Saved Cart",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional specific model SKU variation matrix pointer.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_cart_items",
                        to="catalog.productvariant",
                        verbose_name="Product Variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Cart Item",
                "verbose_name_plural": "Saved Cart Items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialAccountMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("GOOGLE", "Google"),
                            ("FACEBOOK", "Facebook"),
                            ("GITHUB", "GitHub"),
                            ("APPLE", "Apple"),
                            ("OTHER", "Other"),
                        ],
                        max_length=48,
                        verbose_name="Authentication Provider",
                    ),
                ),
                (
                    "provider_uid",
                    models.CharField(
                        db_index=True,
                        help_text="The permanent unique remote key identifier returned by the auth backend ecosystem.",
                        max_length=255,
                        verbose_name="Provider Unique ID",
                    ),
                ),
                (
                    "linked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Linked At"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Synced At"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="customers.customerprofile",
                        verbose_name="Customer Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Account Metadata",
                "verbose_name_plural": "Social Account Metadata Records",
                "ordering": ["-linked_at"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to="customers.customerprofile",
                        verbose_name="Customer Profile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wishlist Item",
                "verbose_name_plural": "Wishlist Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["phone_number"], name="customers_c_phone_n_6eb4be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["preferred_language"], name="customers_c_preferr_87446b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["customer", "is_active"], name="customers_c_custome_e1f892_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["customer", "address_type"],
                name="customers_c_custome_7740eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedcart",
            index=models.Index(
                fields=["customer", "updated_at"], name="customers_s_custome_39c26c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedcartitem",
            index=models.Index(
                fields=["saved_cart", "product"], name="customers_s_saved_c_ac6d54_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="savedcartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", False)),
                fields=("saved_cart", "product", "variant"),
                name="unique_cart_product_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedcartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("saved_cart", "product"),
                name="unique_cart_product_no_variant",
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccountmetadata",
            index=models.Index(
                fields=["provider_uid"], name="customers_s_provide_fbab81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialaccountmetadata",
            index=models.Index(
                fields=["customer", "provider"], name="customers_s_custome_b8031e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="socialaccountmetadata",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_uid"), name="unique_provider_account"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(
                fields=["customer", "product"], name="customers_w_custome_4c2f51_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                fields=("customer", "product"), name="unique_customer_product_wishlist"
            ),
        ),
    ]
