# Generated by Django 5.1.4 on 2026-07-21 17:59

import apps.customers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraddress",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Is Default Address"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="phone_number",
            field=models.CharField(max_length=50, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.customers.models.customer_avatar_upload_path,
                verbose_name="Avatar Image",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="newsletter_subscribed",
            field=models.BooleanField(
                default=False, verbose_name="Newsletter Subscribed"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=32,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="en",
                max_length=16,
                null=True,
                verbose_name="Preferred Language",
            ),
        ),
        migrations.AlterField(
            model_name="savedcart",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Cart Name"),
        ),
        migrations.AlterField(
            model_name="savedcartitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saved_cart_items",
                to="catalog.productvariant",
                verbose_name="Product Variant",
            ),
        ),
        migrations.AlterField(
            model_name="socialaccountmetadata",
            name="provider_uid",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Provider Unique ID"
            ),
        ),
    ]
