# Generated by Django 5.1.4 on 2026-07-23 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customeraddress_full_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customerprofile",
            name="customers_c_preferr_87446b_idx",
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("INDIVIDUAL", "Individual Person"),
                    ("WHOLESALE", "Wholeseller / Retailer"),
                    ("ORGANIZATION", "Organization / Corporate / Bulk Supplier"),
                ],
                db_index=True,
                default="INDIVIDUAL",
                max_length=32,
                verbose_name="Account Classification",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="business_registration_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Company Registration / License Number",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RETAILER", "Retail Store / Boutique"),
                    ("WHOLESALER", "Wholesale Distributor"),
                    ("HOTEL_RESORT", "Hotel / Resort / Hospitality"),
                    ("GOVERNMENT_NGO", "Government / Non-Profit / NGO"),
                    ("PRIVATE_CORP", "Private Enterprise / Corporate"),
                    ("OTHER", "Other Entity Type"),
                ],
                max_length=32,
                null=True,
                verbose_name="Industry / Business Category",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="business_website",
            field=models.URLField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Business Website URL",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="company_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Registered Company / Organization Name",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="country_of_incorporation",
            field=models.CharField(
                blank=True,
                default="Nepal",
                max_length=100,
                null=True,
                verbose_name="Country of Registration / Incorporation",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="is_approved_b2b",
            field=models.BooleanField(
                db_index=True,
                default=True,
                verbose_name="Approved B2B / Wholesale Account",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="tax_id_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Tax Identification Number (Nepal PAN/VAT or International EIN/VAT)",
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["account_type"], name="customers_c_account_ec0836_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["company_name"], name="customers_c_company_c6e53e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["tax_id_number"], name="customers_c_tax_id__77b317_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["country_of_incorporation"],
                name="customers_c_country_842bac_idx",
            ),
        ),
    ]
