# Generated by Django 5.1.4 on 2026-06-25 09:33

import apps.homepage.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtisanStorySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artisan_name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Artisan Name",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.homepage.models._upload_to_homepage_media,
                        verbose_name="Artisan Image",
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        blank=True, null=True, verbose_name="Highlight Quote"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, null=True, verbose_name="Biography / Story"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Button Text"
                    ),
                ),
                (
                    "target_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Target URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Meet The Maker Section",
                "verbose_name_plural": "Meet The Maker Section",
            },
        ),
        migrations.CreateModel(
            name="CategorySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Section Heading",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visual Discovery Section",
                "verbose_name_plural": "Visual Discovery Section",
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Hero Subtitle",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Hero Title"
                    ),
                ),
                (
                    "background_media",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.homepage.models._upload_to_homepage_media,
                        verbose_name="Background Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
            },
        ),
        migrations.CreateModel(
            name="HomepageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page_title",
                    models.CharField(
                        blank=True,
                        help_text="Title tag for the homepage.",
                        max_length=120,
                        null=True,
                        verbose_name="Page Title",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is Homepage Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage Settings",
                "verbose_name_plural": "Homepage Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialProofSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Section Heading",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Proof Section",
                "verbose_name_plural": "Social Proof Section",
            },
        ),
        migrations.CreateModel(
            name="TrendingSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Section Heading",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchandising Carousel",
                "verbose_name_plural": "Merchandising Carousel",
            },
        ),
        migrations.CreateModel(
            name="TrustBarSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Show Trust Bar"),
                ),
            ],
            options={
                "verbose_name": "Trust Bar Section",
                "verbose_name_plural": "Trust Bar Section",
            },
        ),
        migrations.CreateModel(
            name="CategoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.homepage.models._upload_to_homepage_media,
                        verbose_name="Category Image",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Category Target URL",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Display Order"
                    ),
                ),
                (
                    "category_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="homepage.categorysection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Card",
                "verbose_name_plural": "Category Cards",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="HeroCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Button Label",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Target URL"
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("btn-primary", "Primary (Gold)"),
                            ("btn-outline", "Outline (White)"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Button Style",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Display Order"
                    ),
                ),
                (
                    "hero_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ctas",
                        to="homepage.herosection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero CTA Button",
                "verbose_name_plural": "Hero CTA Buttons",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="SocialProofImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.homepage.models._upload_to_homepage_media,
                        verbose_name="UGC Image",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Display Order"
                    ),
                ),
                (
                    "social_proof_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="homepage.socialproofsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Proof Image",
                "verbose_name_plural": "Social Proof Images",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrendingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Product Title",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        help_text="e.g., $120.00",
                        max_length=50,
                        null=True,
                        verbose_name="Display Price",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.homepage.models._upload_to_homepage_media,
                        verbose_name="Product Image",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text="Optional. e.g., 'Only 1 Left', 'New Kiln Run'",
                        max_length=50,
                        null=True,
                        verbose_name="Availability Badge",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Display Order"
                    ),
                ),
                (
                    "trending_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="homepage.trendingsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trending Product",
                "verbose_name_plural": "Trending Products",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrustBarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Matches frontend SVG mapping (e.g., 'fair-trade', 'shipping', 'artisan')",
                        max_length=50,
                        null=True,
                        verbose_name="Icon Key",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Trust Signal Text",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Display Order"
                    ),
                ),
                (
                    "trust_bar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="homepage.trustbarsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Bar Signal",
                "verbose_name_plural": "Trust Bar Signals",
                "ordering": ["position", "id"],
            },
        ),
    ]
