# Generated by Django 5.1.4 on 2026-06-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artisanstorysection",
            name="artisan",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, name, bio, quote, and image will be resolved dynamically from the catalog artisan.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.artisan",
                verbose_name="Linked Catalog Artisan",
            ),
        ),
        migrations.AddField(
            model_name="categoryitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, details like Name and URL will be resolved dynamically from the catalog category.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.category",
                verbose_name="Linked Catalog Category",
            ),
        ),
        migrations.AddField(
            model_name="trendingproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, details like Title, Price, Image and Badge will be resolved dynamically from the catalog product.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.product",
                verbose_name="Linked Catalog Product",
            ),
        ),
    ]
