# Generated by Django 5.1.4 on 2026-07-21 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artisanstorysection",
            name="artisan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.artisan",
                verbose_name="Linked Catalog Artisan",
            ),
        ),
        migrations.AlterField(
            model_name="categorysection",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Section Enabled"),
        ),
        migrations.AlterField(
            model_name="homepagesettings",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Homepage Active"),
        ),
        migrations.AlterField(
            model_name="trendingproduct",
            name="badge",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Availability Badge"
            ),
        ),
        migrations.AlterField(
            model_name="trendingproduct",
            name="price",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Display Price"
            ),
        ),
        migrations.AlterField(
            model_name="trendingproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.product",
                verbose_name="Linked Catalog Product",
            ),
        ),
        migrations.AlterField(
            model_name="trustbarsection",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Show Trust Bar"),
        ),
    ]
