# Generated by Django 5.1.4 on 2026-06-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_artisanstorysection_artisan_categoryitem_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorysection",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Section Description"
            ),
        ),
        migrations.AddField(
            model_name="categorysection",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Section Enabled"
            ),
        ),
        migrations.AlterField(
            model_name="homepagesettings",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Is Homepage Active"
            ),
        ),
        migrations.AlterField(
            model_name="trustbarsection",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Show Trust Bar"
            ),
        ),
        migrations.DeleteModel(
            name="CategoryItem",
        ),
    ]
