# Generated by Django 5.1.4 on 2026-07-16 05:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "product_name_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Product Name (Snapshot)",
                    ),
                ),
                (
                    "product_sku_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Product SKU (Snapshot)",
                    ),
                ),
                (
                    "variant_name_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Variant Name (Snapshot)",
                    ),
                ),
                (
                    "product_image_snapshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cart/snapshots/",
                        verbose_name="Product Image (Snapshot)",
                    ),
                ),
                (
                    "unit_price_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Unit Price (Snapshot)",
                    ),
                ),
                (
                    "compare_at_price_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Compare At Price (Snapshot)",
                    ),
                ),
                (
                    "currency_snapshot",
                    models.CharField(
                        blank=True,
                        default="NPR",
                        max_length=8,
                        null=True,
                        verbose_name="Currency (Snapshot)",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("saved", "Saved For Later"),
                            ("removed", "Removed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "saved_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Manually Saved"),
                            ("replaced", "Replaced By Newer Variant"),
                            ("out_of_stock", "Variant Out Of Stock"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Saved For Later Reason",
                    ),
                ),
                (
                    "attributes_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Selected Attributes (Snapshot)",
                    ),
                ),
                (
                    "personalization",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Engraving text, gift wrapping options, etc.",
                        verbose_name="Personalization Data",
                    ),
                ),
                (
                    "reserved_until",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timezone-aware timestamp until which inventory is reserved for this cart line. Cart-level soft expiry; the inventory app remains the single source of truth for actual stock state and reservation validity.",
                        null=True,
                        verbose_name="Reserved Until",
                    ),
                ),
                (
                    "reservation_token",
                    models.CharField(
                        blank=True,
                        help_text="Opaque identifier of the active StockReservation for this line. Carries no stock data. Used only for cross-system correlation.",
                        max_length=64,
                        null=True,
                        verbose_name="Reservation Token (opaque)",
                    ),
                ),
                (
                    "reservation_status",
                    models.CharField(
                        blank=True,
                        help_text="Mirror of the reservation status for display. The Inventory app's StockReservation is the single source of truth.",
                        max_length=20,
                        null=True,
                        verbose_name="Reservation Status (mirror)",
                    ),
                ),
                (
                    "reservation_expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Mirror of the reservation expiry for display. Actual expiry lives on the StockReservation in the Inventory app.",
                        null=True,
                        verbose_name="Reservation Expires At (mirror)",
                    ),
                ),
                (
                    "reservation_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mirror of the quantity reserved for this line item. The StockReservation in the Inventory app is the single source of truth.",
                        max_digits=14,
                        null=True,
                        verbose_name="Reservation Quantity (mirror)",
                    ),
                ),
                (
                    "reservation_source",
                    models.CharField(
                        blank=True,
                        help_text="Source classification (cart/manual/promotional). The Inventory app is the single source of truth.",
                        max_length=40,
                        null=True,
                        verbose_name="Reservation Source (mirror)",
                    ),
                ),
                (
                    "reservation_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Opaque passthrough metadata. Never contains stock quantities.",
                        verbose_name="Reservation Metadata (mirror)",
                    ),
                ),
                (
                    "reservation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Free-text notes from the reservation for display. The Inventory app is the single source of truth.",
                        null=True,
                        verbose_name="Reservation Notes (mirror)",
                    ),
                ),
                (
                    "reservation_version",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cache-busting version counter mirrored from the StockReservation.",
                        verbose_name="Reservation Version (mirror)",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("saved_at", models.DateTimeField(blank=True, null=True)),
                ("moved_to_save_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
                "ordering": ["added_at"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Anonymous session identifier for guest carts.",
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Session Key",
                    ),
                ),
                (
                    "anonymous_token",
                    models.CharField(
                        blank=True,
                        help_text="Persistent token used to recover abandoned guest carts across devices.",
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Anonymous Cart Token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("merged", "Merged Into Another Cart"),
                            ("abandoned", "Marked Abandoned"),
                            ("converted", "Converted To Order"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("NPR", "Nepalese Rupee"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("INR", "Indian Rupee"),
                        ],
                        default="NPR",
                        max_length=8,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Applied Coupon Code",
                    ),
                ),
                (
                    "coupon_discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Coupon Discount",
                    ),
                ),
                (
                    "customer_note",
                    models.TextField(blank=True, verbose_name="Customer Note"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Last Activity At"
                    ),
                ),
                (
                    "recovered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Recovered At"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this cart is no longer considered valid.",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_merged_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this cart was last merged with another cart.",
                        null=True,
                        verbose_name="Last Merged At",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
                "ordering": ["-last_activity_at"],
            },
        ),
    ]
