# Generated by Django 5.1.4 on 2026-07-16 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="preferred_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional fulfillment preference. Cart never stores stock data; this only records which warehouse the customer would like to draw from. Inventory remains the single source of truth.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_carts",
                to="inventory.warehouse",
                verbose_name="Preferred Warehouse (optional)",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cart.cart",
                verbose_name="Cart",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional reference to the Inventory row backing this cart line. The cart NEVER stores reserved quantity, available quantity, or any other inventory data.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="inventory.inventory",
                verbose_name="Inventory (optional reference)",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional reference to the StockReservation created for this cart line. Cart does NOT store reserved quantity; the reservation itself is the single source of truth.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="inventory.stockreservation",
                verbose_name="Stock Reservation (optional)",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="catalog.productvariant",
                verbose_name="Product Variant",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional explicit warehouse preference for this line. Stock data always remains in the Inventory app.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="inventory.warehouse",
                verbose_name="Warehouse (optional preference)",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["customer", "is_active", "status"],
                name="cart_cart_custome_923f4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["session_key", "is_active", "status"],
                name="cart_cart_session_6a03d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["anonymous_token", "is_active"],
                name="cart_cart_anonymo_4e56ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["last_activity_at"], name="cart_cart_last_ac_39da57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["status", "expires_at"], name="cart_cart_status_19265e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["last_merged_at"], name="cart_cart_last_me_48b800_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["customer", "status", "-last_activity_at"],
                name="cart_active_for_customer_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("anonymous_token",), name="cart_anonymous_token_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("customer__isnull", True),
                    ("session_key__isnull", True),
                    _connector="OR",
                ),
                name="cart_customer_session_xor",
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "status"], name="cart_cartit_cart_id_ca1036_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "product", "variant", "status"],
                name="cart_cartit_cart_id_2f33fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "status", "updated_at"],
                name="cart_cartit_cart_id_e61ddf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["status", "added_at"], name="cart_cartit_status_b8fd2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["status", "reserved_until"], name="cartitem_status_resv_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "status", "reserved_until"],
                name="cartitem_cart_stat_resv_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["reservation_expires_at"], name="cart_cartit_reserva_3bdb8a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True), _negated=True),
                fields=("cart", "product", "variant", "status"),
                name="cart_unique_product_variant_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("cart", "product", "status"),
                name="cart_unique_product_no_variant_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="cartitem_quantity_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price_snapshot__gte", 0)),
                name="cartitem_unit_price_gte_0",
            ),
        ),
    ]
