# Generated by Django 5.1.4 on 2026-07-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_initial"),
        ("inventory", "0003_alter_inventory_damaged_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="preferred_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional fulfillment preference. Inventory remains the single source of truth.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_carts",
                to="inventory.warehouse",
                verbose_name="Preferred Warehouse (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="inventory.inventory",
                verbose_name="Inventory (optional reference)",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="personalization",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Personalization Data"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="inventory.stockreservation",
                verbose_name="Stock Reservation (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="reservation_expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Reservation Expires At (mirror)",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="reservation_metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Reservation Metadata (mirror)"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="reservation_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reservation Notes (mirror)"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="reservation_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Reservation Quantity (mirror)",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="reservation_source",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Reservation Source (mirror)",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="reservation_status",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Reservation Status (mirror)",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="reservation_token",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Reservation Token (opaque)",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="reservation_version",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Reservation Version (mirror)"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="reserved_until",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Reserved Until"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="inventory.warehouse",
                verbose_name="Warehouse (optional preference)",
            ),
        ),
    ]
