# Generated by Django 5.1.4 on 2026-07-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cart_preferred_warehouse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("NPR", "Nepalese Rupee"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("INR", "Indian Rupee"),
                ],
                default="USD",
                max_length=8,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="currency_snapshot",
            field=models.CharField(
                blank=True,
                default="USD",
                max_length=8,
                null=True,
                verbose_name="Currency (Snapshot)",
            ),
        ),
    ]
