# Generated by Django 5.1.4 on 2026-07-23 10:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_alter_artisan_region_and_more"),
        ("orders", "0002_remove_couponusage_coupon_usage_discount_gte_0_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponCMSSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enable_coupon_system",
                    models.BooleanField(
                        default=True, verbose_name="Enable Coupon System System-Wide"
                    ),
                ),
                (
                    "show_public_coupons_in_cart",
                    models.BooleanField(
                        default=True,
                        verbose_name="Show Available Coupons List in Cart/Checkout",
                    ),
                ),
                (
                    "public_section_title",
                    models.CharField(
                        default="Available Craft Offers & Vouchers",
                        max_length=150,
                        verbose_name="Public Coupon Widget Title",
                    ),
                ),
                (
                    "public_section_subtitle",
                    models.CharField(
                        blank=True,
                        default="Apply a voucher code below to enjoy exclusive artisan savings.",
                        max_length=255,
                        null=True,
                        verbose_name="Public Coupon Widget Subtitle",
                    ),
                ),
                (
                    "banner_message",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Cart Coupon Promotional Announcement Banner",
                    ),
                ),
                (
                    "auto_apply_best_coupon",
                    models.BooleanField(
                        default=False,
                        verbose_name="Auto-Apply Best Qualifying Coupon Automatically",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon CMS Settings",
                "verbose_name_plural": "Coupon CMS Settings",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Case-insensitive uppercase coupon code (e.g., HANDICRAFT10).",
                        max_length=50,
                        unique=True,
                        verbose_name="Coupon Code",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Offer Title / Headline"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Terms & Conditions Description",
                    ),
                ),
                (
                    "promo_badge_text",
                    models.CharField(
                        blank=True,
                        help_text="Short tag displayed on product cards/cart (e.g., '15% OFF').",
                        max_length=60,
                        null=True,
                        verbose_name="Public Badge Text",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Discount (%)"),
                            ("fixed_amount", "Fixed Amount Discount"),
                            ("free_shipping", "Free Shipping Discount"),
                            ("buy_x_get_y", "Buy X Get Y Free"),
                        ],
                        db_index=True,
                        default="percentage",
                        max_length=20,
                        verbose_name="Discount Calculation Type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or fixed amount value depending on calculation type.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Discount Value",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional cap for percentage discounts.",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Maximum Discount Cap (NPR)",
                    ),
                ),
                (
                    "min_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Minimum Order Subtotal (NPR)",
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("all", "Entire Store / All Products"),
                            ("products", "Specific Products Only"),
                            ("categories", "Specific Categories Only"),
                            ("artisans", "Specific Master Artisans Only"),
                            ("collections", "Specific Craft Collections Only"),
                        ],
                        db_index=True,
                        default="all",
                        max_length=20,
                        verbose_name="Product Targeting Scope",
                    ),
                ),
                (
                    "customer_scope",
                    models.CharField(
                        choices=[
                            ("all", "All Customers & Guests"),
                            ("first_time", "First-Time Buyers Only"),
                            ("premium", "Subscribed / Premium Members"),
                            ("specific", "Specific Customer Accounts"),
                        ],
                        db_index=True,
                        default="all",
                        max_length=20,
                        verbose_name="Customer Eligibility Scope",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Activation Start Date",
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Expiration End Date",
                    ),
                ),
                (
                    "usage_limit_total",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum total times this coupon can be redeemed platform-wide.",
                        null=True,
                        verbose_name="Global Total Usage Limit",
                    ),
                ),
                (
                    "usage_limit_per_user",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Usage Limit Per Customer",
                    ),
                ),
                (
                    "times_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Times Redeemed Counter"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Is Publicly Displayed in Store",
                    ),
                ),
                (
                    "auto_apply",
                    models.BooleanField(
                        default=False, verbose_name="Auto-Apply to Cart when Qualified"
                    ),
                ),
                (
                    "stackable",
                    models.BooleanField(
                        default=False, verbose_name="Can Stack With Other Coupons"
                    ),
                ),
                (
                    "exclude_sale_items",
                    models.BooleanField(
                        default=False, verbose_name="Exclude Sale / Discounted Products"
                    ),
                ),
                (
                    "target_artisans",
                    models.ManyToManyField(
                        blank=True,
                        related_name="targeted_coupons",
                        to="catalog.artisan",
                        verbose_name="Target Master Artisans",
                    ),
                ),
                (
                    "target_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="targeted_coupons",
                        to="catalog.category",
                        verbose_name="Target Categories",
                    ),
                ),
                (
                    "target_collections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="targeted_coupons",
                        to="catalog.productcollection",
                        verbose_name="Target Craft Collections",
                    ),
                ),
                (
                    "target_customers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Specific Eligible Customers",
                    ),
                ),
                (
                    "target_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="targeted_coupons",
                        to="catalog.product",
                        verbose_name="Target Products",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon Voucher",
                "verbose_name_plural": "Coupon Vouchers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Discount Amount Applied (NPR)",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Redemption Timestamp",
                    ),
                ),
                (
                    "is_reversed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Is Reversed / Cancelled",
                    ),
                ),
                (
                    "reversal_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Reversal Reason"
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_records",
                        to="coupons.coupon",
                        verbose_name="Coupon",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_redemption_records",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_redemptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon Usage Ledger Record",
                "verbose_name_plural": "Coupon Usage Ledger Records",
                "ordering": ["-used_at"],
            },
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["code", "is_active"], name="coupons_cou_code_1aa9c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["is_active", "is_public"], name="coupons_cou_is_acti_e2f007_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["valid_from", "valid_to"], name="coupons_cou_valid_f_cf442c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["target_scope", "customer_scope"],
                name="coupons_cou_target__715c9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="couponusagerecord",
            index=models.Index(
                fields=["coupon", "user"], name="coupons_cou_coupon__73d17d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="couponusagerecord",
            index=models.Index(
                fields=["order", "is_reversed"], name="coupons_cou_order_i_a8ea56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="couponusagerecord",
            index=models.Index(
                fields=["used_at"], name="coupons_cou_used_at_6b7d0a_idx"
            ),
        ),
    ]
