# Generated by Django 5.1.4 on 2026-07-31 19:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="max_discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional cap for percentage discounts.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Maximum Discount Cap (US$)",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="min_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Minimum Order Subtotal (US$)",
            ),
        ),
        migrations.AlterField(
            model_name="couponusagerecord",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Discount Amount Applied (US$)",
            ),
        ),
    ]
