# Generated by Django 5.1.4 on 2026-07-23 15:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_remove_couponusage_coupon_usage_discount_gte_0_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enable_esewa",
                    models.BooleanField(
                        default=True, verbose_name="Enable eSewa Wallet (Nepal)"
                    ),
                ),
                (
                    "esewa_merchant_code",
                    models.CharField(
                        default="EPAYTEST",
                        max_length=100,
                        verbose_name="eSewa Merchant Code",
                    ),
                ),
                (
                    "esewa_secret_key",
                    models.CharField(
                        default="8gBm9-W3B2-yA4z",
                        max_length=255,
                        verbose_name="eSewa Secret Key (HMAC SHA256)",
                    ),
                ),
                (
                    "esewa_is_sandbox",
                    models.BooleanField(
                        default=True, verbose_name="eSewa Sandbox Mode"
                    ),
                ),
                (
                    "enable_khalti",
                    models.BooleanField(
                        default=True, verbose_name="Enable Khalti Wallet (Nepal)"
                    ),
                ),
                (
                    "khalti_public_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Khalti Public Key",
                    ),
                ),
                (
                    "khalti_secret_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Khalti Secret Key",
                    ),
                ),
                (
                    "khalti_is_sandbox",
                    models.BooleanField(
                        default=True, verbose_name="Khalti Sandbox Mode"
                    ),
                ),
                (
                    "enable_stripe",
                    models.BooleanField(
                        default=True,
                        verbose_name="Enable Stripe Credit/Debit Card (Global)",
                    ),
                ),
                (
                    "stripe_publishable_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stripe Publishable Key",
                    ),
                ),
                (
                    "stripe_secret_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stripe Secret Key",
                    ),
                ),
                (
                    "stripe_webhook_secret",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stripe Webhook Secret",
                    ),
                ),
                (
                    "enable_cod",
                    models.BooleanField(
                        default=True, verbose_name="Enable Cash on Delivery (COD)"
                    ),
                ),
                (
                    "cod_instructions",
                    models.TextField(
                        blank=True,
                        default="Pay cash directly to our delivery representative upon order arrival.",
                        null=True,
                        verbose_name="COD Instructions for Customer",
                    ),
                ),
                (
                    "enable_bank_transfer",
                    models.BooleanField(
                        default=True, verbose_name="Enable Direct Bank Wire Transfer"
                    ),
                ),
                (
                    "bank_transfer_instructions",
                    models.TextField(
                        blank=True,
                        default="Bank Name: Nabil Bank Ltd.\nAccount Name: Gobindas Handicrafts Pvt. Ltd.\nAccount No: 0120017500101\nBranch: Kathmandu",
                        null=True,
                        verbose_name="Bank Transfer Instructions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Gateway Settings",
                "verbose_name_plural": "Payment Gateway Settings",
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("esewa", "eSewa Mobile Wallet (Nepal)"),
                            ("khalti", "Khalti Digital Wallet (Nepal)"),
                            ("stripe", "Stripe Credit/Debit Card (International)"),
                            ("cod", "Cash on Delivery (COD)"),
                            ("bank_transfer", "Direct Bank Wire Transfer"),
                        ],
                        max_length=50,
                        verbose_name="Gateway Source",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(default=dict, verbose_name="Webhook Request Body"),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, verbose_name="Is Processed Successfully"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Details (if any)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Webhook Log",
                "verbose_name_plural": "Payment Webhook Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Transaction Reference ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("esewa", "eSewa Mobile Wallet (Nepal)"),
                            ("khalti", "Khalti Digital Wallet (Nepal)"),
                            ("stripe", "Stripe Credit/Debit Card (International)"),
                            ("cod", "Cash on Delivery (COD)"),
                            ("bank_transfer", "Direct Bank Wire Transfer"),
                        ],
                        db_index=True,
                        default="cod",
                        max_length=50,
                        verbose_name="Payment Gateway",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Amount Paid",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NPR", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("initiated", "Payment Initiated at Gateway"),
                            ("processing", "Processing Verification"),
                            ("success", "Payment Successful / Captured"),
                            ("failed", "Payment Failed"),
                            ("refunded", "Fully Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("cancelled", "Transaction Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Transaction Status",
                    ),
                ),
                (
                    "gateway_reference_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Gateway Unique Reference / PIDX / Intent ID",
                    ),
                ),
                (
                    "raw_request_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Gateway Request Payload Snapshot",
                    ),
                ),
                (
                    "raw_response_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Gateway Response Payload Snapshot",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Paid Timestamp"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Customer IP Address"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_id", "status"],
                        name="payments_pa_transac_cfd8e3_idx",
                    ),
                    models.Index(
                        fields=["order", "status"],
                        name="payments_pa_order_i_ed562a_idx",
                    ),
                ],
            },
        ),
    ]
