# Generated by Django 5.1.4 on 2026-07-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="currency",
            field=models.CharField(
                default="USD", max_length=10, verbose_name="Currency"
            ),
        ),
    ]
