# Generated by Django 5.1.4 on 2026-06-22 16:46

import apps.foundation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeaderBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency_label",
                    models.CharField(
                        blank=True,
                        help_text="Example: USD",
                        max_length=20,
                        null=True,
                        verbose_name="Currency Label",
                    ),
                ),
                (
                    "language_label",
                    models.CharField(
                        blank=True,
                        help_text="Example: EN",
                        max_length=20,
                        null=True,
                        verbose_name="Language Label",
                    ),
                ),
                (
                    "announcement_messages",
                    models.JSONField(
                        blank=True,
                        help_text="JSON list of campaign/announcement strings shown in the rotator.",
                        null=True,
                        verbose_name="Announcement Messages",
                    ),
                ),
                (
                    "rotator_interval_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Example: 4000",
                        null=True,
                        verbose_name="Rotator Interval (ms)",
                    ),
                ),
                (
                    "left_utilities",
                    models.JSONField(
                        blank=True,
                        help_text="JSON list of left-side utility objects (dropdowns/labels).",
                        null=True,
                        verbose_name="Left Utility Items",
                    ),
                ),
                (
                    "right_utilities",
                    models.JSONField(
                        blank=True,
                        help_text="JSON list of right-side utility objects (links/buttons).",
                        null=True,
                        verbose_name="Right Utility Items",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Bar",
                "verbose_name_plural": "Header Bar",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logo",
                    models.ImageField(
                        help_text="Mandatory site logo upload. Optimization to <= 500KB is handled in the service layer.",
                        upload_to=apps.foundation.models._upload_to_site_logo,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "logo_alt_text",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="Logo Alt Text",
                    ),
                ),
                (
                    "brand_title",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Brand Title",
                    ),
                ),
                (
                    "brand_subtitle",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Brand Subtitle",
                    ),
                ),
                (
                    "brand_url",
                    models.URLField(blank=True, null=True, verbose_name="Brand Link"),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="NavbarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Visible menu label.",
                        max_length=120,
                        verbose_name="Label",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional. Can be empty for mega menu parents or section labels.",
                        max_length=500,
                        null=True,
                        verbose_name="Link URL",
                    ),
                ),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("link", "Link"),
                            ("dropdown", "Dropdown"),
                            ("mega_menu", "Mega Menu"),
                        ],
                        help_text="Controls how the item renders in the frontend.",
                        max_length=20,
                        verbose_name="Menu Type",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Lower numbers appear first.",
                        null=True,
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        help_text="Example: Eco-Friendly, New, Hot",
                        max_length=50,
                        null=True,
                        verbose_name="Badge Text",
                    ),
                ),
                (
                    "badge_style",
                    models.CharField(
                        blank=True,
                        help_text="Optional CSS hook for badge styling.",
                        max_length=50,
                        null=True,
                        verbose_name="Badge Style",
                    ),
                ),
                (
                    "visibility_scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all", "All Devices"),
                            ("desktop", "Desktop Only"),
                            ("mobile", "Mobile Only"),
                        ],
                        help_text="Optional device visibility rule.",
                        max_length=20,
                        null=True,
                        verbose_name="Visibility Scope",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for mega menu media block.",
                        null=True,
                        upload_to=apps.foundation.models._upload_to_navbar_media,
                        verbose_name="Featured Image",
                    ),
                ),
                (
                    "featured_title",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="Featured Title",
                    ),
                ),
                (
                    "featured_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Featured Text"
                    ),
                ),
                (
                    "mega_menu_columns",
                    models.JSONField(
                        blank=True,
                        help_text="JSON list of column objects. Each object can contain a heading and a list of links.",
                        null=True,
                        verbose_name="Mega Menu Columns",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for top-level items.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="foundation.navbaritem",
                        verbose_name="Parent Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navbar Item",
                "verbose_name_plural": "Navbar Items",
                "ordering": ["position", "label", "id"],
                "indexes": [
                    models.Index(
                        fields=["parent", "position"],
                        name="foundation__parent__1a3864_idx",
                    ),
                    models.Index(
                        fields=["menu_type"], name="foundation__menu_ty_b71f6e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent", "label"), name="uniq_navbar_item_parent_label"
                    )
                ],
            },
        ),
    ]
