# Generated by Django 5.1.4 on 2026-06-25 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Payment Gateway Platform Name",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="Identical lookup key strings matching asset mappings (e.g., 'visa', 'mastercard', 'paypal').",
                        max_length=50,
                        null=True,
                        verbose_name="Icon Library Token Lookup Match",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Horizontal Layout Render Alignment Index Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Payment Method",
                "verbose_name_plural": "Footer Payment Methods",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="FooterSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Header layout title showing over lists of custom links.",
                        max_length=120,
                        null=True,
                        verbose_name="Section Column Title",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Lower numeric positions dictate layout prioritization ordering left-to-right.",
                        null=True,
                        verbose_name="Display Order Position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Section",
                "verbose_name_plural": "Footer Sections",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand_name",
                    models.CharField(
                        blank=True,
                        help_text="Main brand title visible inside the footer brand block.",
                        max_length=120,
                        null=True,
                        verbose_name="Brand Name",
                    ),
                ),
                (
                    "fair_trade_statement",
                    models.TextField(
                        blank=True,
                        help_text="A short paragraph highlighting ethical commitments and trust value propositions.",
                        null=True,
                        verbose_name="Fair Trade / Trust Statement",
                    ),
                ),
                (
                    "newsletter_heading",
                    models.CharField(
                        blank=True,
                        help_text="Heading text over the newsletter email input field.",
                        max_length=120,
                        null=True,
                        verbose_name="Newsletter Heading",
                    ),
                ),
                (
                    "newsletter_subtext",
                    models.TextField(
                        blank=True,
                        help_text="Descriptive helper text beneath or above the newsletter input field.",
                        null=True,
                        verbose_name="Newsletter Subtext",
                    ),
                ),
                (
                    "newsletter_endpoint",
                    models.CharField(
                        blank=True,
                        help_text="API action URL target route where newsletter forms execute submissions.",
                        max_length=500,
                        null=True,
                        verbose_name="Newsletter Submission Endpoint",
                    ),
                ),
                (
                    "newsletter_placeholder",
                    models.CharField(
                        blank=True,
                        help_text="Default context text visibility inside empty email fields.",
                        max_length=120,
                        null=True,
                        verbose_name="Newsletter Input Placeholder",
                    ),
                ),
                (
                    "copyright_template",
                    models.CharField(
                        blank=True,
                        help_text="Template pattern string. Accepts tags like {current_year} and {brand_name}.",
                        max_length=255,
                        null=True,
                        verbose_name="Copyright Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Settings",
                "verbose_name_plural": "Footer Settings",
            },
        ),
        migrations.CreateModel(
            name="FooterSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Platform Name ID Reference",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Profile URL Destination Path",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="Identical key matched internally inside standard lookup arrays (e.g., 'instagram', 'pinterest').",
                        max_length=50,
                        null=True,
                        verbose_name="Icon Library Key Lookup Reference",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Layout Placement Sort Index Position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Social Link",
                "verbose_name_plural": "Footer Social Links",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="FooterTrustBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "badge_name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Trust Certification Title / Tag",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="System programmatic map token ID index keys (e.g., 'fair-trade', 'climate-neutral').",
                        max_length=50,
                        null=True,
                        verbose_name="Icon Library Vector ID Token Key",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Display Sorting Priority Sequence Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Trust Badge",
                "verbose_name_plural": "Footer Trust Badges",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Link Text Label",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        help_text="The destination target pathname reference context or full web path link URL.",
                        max_length=500,
                        null=True,
                        verbose_name="Link Target Route / URL",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        blank=True,
                        help_text="Configured types like 'internal_route', 'external_url', or 'action_trigger'.",
                        max_length=50,
                        null=True,
                        verbose_name="Link Action Type System",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Optional identifier parsed to trigger specialized UI events like modal windows.",
                        max_length=120,
                        null=True,
                        verbose_name="Trigger Action ID Hook",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ascending numeric configurations control programmatic layout sorting rules top-to-bottom.",
                        null=True,
                        verbose_name="Link Vertical Sort Index Position",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="foundation.footersection",
                        verbose_name="Parent Section Column",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Link",
                "verbose_name_plural": "Footer Links",
                "ordering": ["position", "id"],
            },
        ),
    ]
