# Generated by Django 5.1.4 on 2026-07-16 05:46

import apps.foundation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hero_title",
                    models.CharField(
                        blank=True,
                        help_text="Main heading displayed in the hero banner of the Contact Page.",
                        max_length=255,
                        null=True,
                        verbose_name="Hero Title",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Supporting subtitle text below the hero title.",
                        max_length=255,
                        null=True,
                        verbose_name="Hero Subtitle",
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        blank=True,
                        help_text="Paragraph description shown in the hero section.",
                        null=True,
                        verbose_name="Hero Description",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional large background/featured image for the contact page hero banner.",
                        null=True,
                        upload_to=apps.foundation.models._upload_to_contact_media,
                        verbose_name="Hero Background Image",
                    ),
                ),
                (
                    "intro_heading",
                    models.CharField(
                        blank=True,
                        help_text="Main intro title displayed prior to physical and communication details.",
                        max_length=255,
                        null=True,
                        verbose_name="Intro Heading",
                    ),
                ),
                (
                    "intro_text",
                    models.TextField(
                        blank=True,
                        help_text="Brief general contact text block.",
                        null=True,
                        verbose_name="Intro Description Text",
                    ),
                ),
                (
                    "address_heading",
                    models.CharField(
                        blank=True,
                        help_text="Heading label for the physical location section.",
                        max_length=255,
                        null=True,
                        verbose_name="Address Heading",
                    ),
                ),
                (
                    "physical_address",
                    models.TextField(
                        blank=True,
                        help_text="Multi-line physical location address text.",
                        null=True,
                        verbose_name="Physical Address",
                    ),
                ),
                (
                    "map_heading",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Map Section Heading",
                    ),
                ),
                (
                    "map_embed_url",
                    models.TextField(
                        blank=True,
                        help_text="Standard iframe source URL containing the customized embedded location link.",
                        null=True,
                        verbose_name="Google Map Embed URL",
                    ),
                ),
                (
                    "hours_heading",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Office Hours Heading",
                    ),
                ),
                (
                    "hours_description",
                    models.TextField(
                        blank=True,
                        help_text="Supporting caption details under the office hours heading.",
                        null=True,
                        verbose_name="Office Hours Description Text",
                    ),
                ),
                (
                    "form_heading",
                    models.CharField(
                        blank=True,
                        help_text="Header layout title displayed above the interactive submission form.",
                        max_length=255,
                        null=True,
                        verbose_name="Form Section Heading",
                    ),
                ),
                (
                    "form_subheading",
                    models.CharField(
                        blank=True,
                        help_text="Brief subtitle or prompt guiding user input.",
                        max_length=255,
                        null=True,
                        verbose_name="Form Section Subheading",
                    ),
                ),
                (
                    "form_submit_button_label",
                    models.CharField(
                        blank=True,
                        help_text="Clickable submission action button text value.",
                        max_length=120,
                        null=True,
                        verbose_name="Form Submit Button Text",
                    ),
                ),
                (
                    "form_success_message",
                    models.TextField(
                        blank=True,
                        help_text="Popup or banner alert text appearing upon successful verification submissions.",
                        null=True,
                        verbose_name="Form Success Feedback Message",
                    ),
                ),
                (
                    "seo_meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Custom title tag optimized specifically for search engines.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Meta Title",
                    ),
                ),
                (
                    "seo_meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Search engine index description text snippets.",
                        null=True,
                        verbose_name="SEO Meta Description",
                    ),
                ),
                (
                    "seo_meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords mapping search engine priority references.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Meta Keywords",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Page Settings",
                "verbose_name_plural": "Contact Page Settings",
            },
        ),
        migrations.CreateModel(
            name="FooterPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Payment Gateway Platform Name",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="Identical lookup key strings matching asset mappings (e.g., 'visa', 'mastercard', 'paypal').",
                        max_length=50,
                        null=True,
                        verbose_name="Icon Library Token Lookup Match",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Horizontal Layout Render Alignment Index Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Payment Method",
                "verbose_name_plural": "Footer Payment Methods",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="FooterSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Header layout title showing over lists of custom links.",
                        max_length=120,
                        null=True,
                        verbose_name="Section Column Title",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Lower numeric positions dictate layout prioritization ordering left-to-right.",
                        null=True,
                        verbose_name="Display Order Position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Section",
                "verbose_name_plural": "Footer Sections",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional logo image dedicated to the footer section.",
                        null=True,
                        upload_to="footer/",
                        verbose_name="Footer Logo",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        blank=True,
                        help_text="Main brand title visible inside the footer brand block.",
                        max_length=120,
                        null=True,
                        verbose_name="Brand Name",
                    ),
                ),
                (
                    "fair_trade_statement",
                    models.TextField(
                        blank=True,
                        help_text="A short paragraph highlighting ethical commitments and trust value propositions.",
                        null=True,
                        verbose_name="Fair Trade / Trust Statement",
                    ),
                ),
                (
                    "newsletter_heading",
                    models.CharField(
                        blank=True,
                        help_text="Heading text over the newsletter email input field.",
                        max_length=120,
                        null=True,
                        verbose_name="Newsletter Heading",
                    ),
                ),
                (
                    "newsletter_subtext",
                    models.TextField(
                        blank=True,
                        help_text="Descriptive helper text beneath or above the newsletter input field.",
                        null=True,
                        verbose_name="Newsletter Subtext",
                    ),
                ),
                (
                    "newsletter_endpoint",
                    models.CharField(
                        blank=True,
                        help_text="API action URL target route where newsletter forms execute submissions.",
                        max_length=500,
                        null=True,
                        verbose_name="Newsletter Submission Endpoint",
                    ),
                ),
                (
                    "newsletter_placeholder",
                    models.CharField(
                        blank=True,
                        help_text="Default context text visibility inside empty email fields.",
                        max_length=120,
                        null=True,
                        verbose_name="Newsletter Input Placeholder",
                    ),
                ),
                (
                    "copyright_template",
                    models.CharField(
                        blank=True,
                        help_text="Template pattern string. Accepts tags like {current_year} and {brand_name}.",
                        max_length=255,
                        null=True,
                        verbose_name="Copyright Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Settings",
                "verbose_name_plural": "Footer Settings",
            },
        ),
        migrations.CreateModel(
            name="FooterSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Platform Name ID Reference",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Profile URL Destination Path",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="Identical key matched internally inside standard lookup arrays (e.g., 'instagram', 'pinterest').",
                        max_length=50,
                        null=True,
                        verbose_name="Icon Library Key Lookup Reference",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="CSS class for the icon (e.g., 'fab fa-facebook-f'). Allows dynamic config without code changes.",
                        max_length=255,
                        null=True,
                        verbose_name="Icon CSS Class",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Layout Placement Sort Index Position",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Control if this social link is active and visible.",
                        verbose_name="Is Visible",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Social Link",
                "verbose_name_plural": "Footer Social Links",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="FooterTrustBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "badge_name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Trust Certification Title / Tag",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="System programmatic map token ID index keys (e.g., 'fair-trade', 'climate-neutral').",
                        max_length=50,
                        null=True,
                        verbose_name="Icon Library Vector ID Token Key",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Display Sorting Priority Sequence Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Trust Badge",
                "verbose_name_plural": "Footer Trust Badges",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="NavbarSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Enable Main Navigation"
                    ),
                ),
                (
                    "is_sticky",
                    models.BooleanField(
                        default=True,
                        help_text="Keep navigation pinned to top while scrolling.",
                        verbose_name="Sticky Navigation",
                    ),
                ),
                (
                    "desktop_behavior",
                    models.CharField(
                        choices=[
                            ("hover", "Open on Hover"),
                            ("click", "Open on Click"),
                        ],
                        default="hover",
                        max_length=50,
                        verbose_name="Desktop Navigation Behavior",
                    ),
                ),
                (
                    "mobile_behavior",
                    models.CharField(
                        choices=[
                            ("accordion", "Accordion Menu"),
                            ("offcanvas", "Offcanvas Menu"),
                        ],
                        default="offcanvas",
                        max_length=50,
                        verbose_name="Mobile Navigation Behavior",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navbar Settings",
                "verbose_name_plural": "Navbar Settings",
            },
        ),
        migrations.RemoveField(
            model_name="navbaritem",
            name="mega_menu_columns",
        ),
        migrations.AddField(
            model_name="headerbar",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Globally toggle the visibility of the entire top header bar.",
                verbose_name="Enable Header Bar",
            ),
        ),
        migrations.AddField(
            model_name="headerbar",
            name="is_sticky",
            field=models.BooleanField(
                default=False,
                help_text="Pin the header bar to the top of the viewport when scrolling.",
                verbose_name="Sticky Header Bar",
            ),
        ),
        migrations.AddField(
            model_name="headerbar",
            name="show_on_desktop",
            field=models.BooleanField(
                default=True, verbose_name="Show on Desktop Devices"
            ),
        ),
        migrations.AddField(
            model_name="headerbar",
            name="show_on_mobile",
            field=models.BooleanField(
                default=True, verbose_name="Show on Mobile Devices"
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Activation End Date"
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="featured_cta_text",
            field=models.CharField(
                blank=True,
                help_text="Button text for the featured media block.",
                max_length=120,
                null=True,
                verbose_name="Featured CTA Text",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="featured_cta_url",
            field=models.CharField(
                blank=True,
                help_text="Button URL target for the featured media block.",
                max_length=500,
                null=True,
                verbose_name="Featured CTA URL",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="featured_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule when to stop showing the featured block.",
                null=True,
                verbose_name="Featured Media End Date",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="featured_is_visible",
            field=models.BooleanField(
                default=True, verbose_name="Featured Media Block Visibility"
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="featured_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule when to start showing the featured block.",
                null=True,
                verbose_name="Featured Media Start Date",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="icon_key",
            field=models.CharField(
                blank=True,
                help_text="Optional icon identifier for display next to label.",
                max_length=50,
                null=True,
                verbose_name="Icon Key",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="open_in_new_tab",
            field=models.BooleanField(default=False, verbose_name="Open in New Tab"),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="requires_authentication",
            field=models.BooleanField(
                default=False,
                help_text="If checked, item is only visible to logged-in users.",
                verbose_name="Requires Authentication",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Optional identifier for referencing within codebase.",
                max_length=120,
                null=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Activation Start Date"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cart_badge_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=2,
                help_text="Dynamic count badge shown on the header cart button.",
                null=True,
                verbose_name="Cart Badge Count",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cart_button_label",
            field=models.CharField(
                blank=True,
                default="Shopping Bag",
                help_text="Accessibility label/text for the cart button.",
                max_length=120,
                null=True,
                verbose_name="Cart Button Label",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Fallback featured image for mega menus when no specific image is provided.",
                null=True,
                upload_to=apps.foundation.models._upload_to_navbar_media,
                verbose_name="Default Mega Menu Featured Image",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_featured_text",
            field=models.TextField(
                blank=True,
                default="Explore the workshop lineages of India.",
                help_text="Fallback featured description text for mega menus.",
                null=True,
                verbose_name="Default Mega Menu Featured Text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_featured_title",
            field=models.CharField(
                blank=True,
                default="Meet the Artisans",
                help_text="Fallback featured title for mega menus.",
                max_length=160,
                null=True,
                verbose_name="Default Mega Menu Featured Title",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_customer_registration",
            field=models.BooleanField(
                default=True,
                help_text="Globally enable or disable new customer account registration pages and buttons.",
                verbose_name="Enable Customer Registration",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_facebook_login",
            field=models.BooleanField(
                default=True,
                help_text="Allow customers to log in using their Facebook accounts (if Social Login is enabled).",
                verbose_name="Enable Facebook Login",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_github_login",
            field=models.BooleanField(
                default=False,
                help_text="Allow customers to log in using their GitHub accounts (if Social Login is enabled).",
                verbose_name="Enable GitHub Login",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_google_login",
            field=models.BooleanField(
                default=True,
                help_text="Allow customers to log in using their Google accounts (if Social Login is enabled).",
                verbose_name="Enable Google Login",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_guest_checkout",
            field=models.BooleanField(
                default=True,
                help_text="Globally allow or restrict customers from checking out without creating an account.",
                verbose_name="Enable Guest Checkout",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_social_login",
            field=models.BooleanField(
                default=True,
                help_text="Globally enable or disable social authentication (SSO) flows.",
                verbose_name="Enable Social Login",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_link",
            field=models.CharField(
                blank=True,
                default="/",
                help_text="The destination URL when the brand logo is clicked.",
                max_length=500,
                null=True,
                verbose_name="Logo Link URL",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mobile_logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional separate logo optimized for mobile devices.",
                null=True,
                upload_to=apps.foundation.models._upload_to_site_logo,
                verbose_name="Mobile Logo",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="search_button_label",
            field=models.CharField(
                blank=True,
                default="Search",
                help_text="Accessibility label/text for the search button.",
                max_length=120,
                null=True,
                verbose_name="Search Button Label",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="search_placeholder",
            field=models.CharField(
                blank=True,
                default="Find artisan rugs...",
                help_text="Placeholder text shown inside the global header search input.",
                max_length=255,
                null=True,
                verbose_name="Search Placeholder",
            ),
        ),
        migrations.CreateModel(
            name="ContactOfficeHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Monday, Monday - Friday, Weekends",
                        max_length=120,
                        null=True,
                        verbose_name="Day/Day Range",
                    ),
                ),
                (
                    "opening_time",
                    models.CharField(
                        blank=True,
                        help_text="Custom time format string (e.g., '9:00 AM', '09:00').",
                        max_length=120,
                        null=True,
                        verbose_name="Opening Time",
                    ),
                ),
                (
                    "closing_time",
                    models.CharField(
                        blank=True,
                        help_text="Custom time format string (e.g., '5:00 PM', '17:00').",
                        max_length=120,
                        null=True,
                        verbose_name="Closing Time",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("by_appointment", "By Appointment Only"),
                        ],
                        default="open",
                        help_text="System state for the scheduled timeframe display.",
                        max_length=50,
                        null=True,
                        verbose_name="Operating Status",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ascending sort position order values controlling tabular render ranking.",
                        null=True,
                        verbose_name="Display Order Position",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle operating schedule visibility.",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "contact_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_hours",
                        to="foundation.contactpage",
                        verbose_name="Parent Contact Page Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Office Hour",
                "verbose_name_plural": "Contact Office Hours",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Customer Care, Press/PR",
                        max_length=120,
                        null=True,
                        verbose_name="Email Label/Department",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Valid email reference target destination.",
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Lower numeric positions dictate vertical sort priority ranking.",
                        null=True,
                        verbose_name="Display Order Position",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Control if this email entry is visible on the frontend page.",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "contact_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="foundation.contactpage",
                        verbose_name="Parent Contact Page Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Email",
                "verbose_name_plural": "Contact Emails",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="e.g., General Inquiries, Technical Support",
                        max_length=120,
                        null=True,
                        verbose_name="Phone Label/Department",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Callable phone number value.",
                        max_length=50,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Lower numeric positions dictate vertical sort priority ranking.",
                        null=True,
                        verbose_name="Display Order Position",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Control if this phone entry is visible on the frontend page.",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "contact_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="foundation.contactpage",
                        verbose_name="Parent Contact Page Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Phone",
                "verbose_name_plural": "Contact Phones",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Platform Name",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Profile URL Destination Path",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="System programmatic token to map vector icon assets (e.g., 'instagram', 'pinterest').",
                        max_length=50,
                        null=True,
                        verbose_name="Icon Library Key Lookup Reference",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="CSS class for the icon (e.g., 'fab fa-facebook-f'). Allows dynamic config without code changes.",
                        max_length=255,
                        null=True,
                        verbose_name="Icon CSS Class",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Display Order Position"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Control if this social link is active and visible.",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "contact_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="foundation.contactpage",
                        verbose_name="Parent Contact Page Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Social Link",
                "verbose_name_plural": "Contact Social Links",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Link Text Label",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        help_text="The destination target pathname reference context or full web path link URL.",
                        max_length=500,
                        null=True,
                        verbose_name="Link Target Route / URL",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        blank=True,
                        help_text="Configured types like 'internal_route', 'external_url', or 'action_trigger'.",
                        max_length=50,
                        null=True,
                        verbose_name="Link Action Type System",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Optional identifier parsed to trigger specialized UI events like modal windows.",
                        max_length=120,
                        null=True,
                        verbose_name="Trigger Action ID Hook",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ascending numeric configurations control programmatic layout sorting rules top-to-bottom.",
                        null=True,
                        verbose_name="Link Vertical Sort Index Position",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="foundation.footersection",
                        verbose_name="Parent Section Column",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Link",
                "verbose_name_plural": "Footer Links",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="HeaderAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "text",
                    models.CharField(
                        help_text="Message text shown in the announcement rotator.",
                        max_length=255,
                        verbose_name="Announcement Text",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when this announcement should start displaying.",
                        null=True,
                        verbose_name="Activation Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when this announcement should stop displaying.",
                        null=True,
                        verbose_name="Activation End Date",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher numbers take precedence if multiple announcements overlap.",
                        verbose_name="Priority Sequence",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers display first.",
                        verbose_name="Display Order Position",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Control if this announcement is active and visible.",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "header_bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="foundation.headerbar",
                        verbose_name="Header Bar Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Announcement",
                "verbose_name_plural": "Header Announcements",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="HeaderCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Example: United States",
                        max_length=100,
                        verbose_name="Country Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Example: US",
                        max_length=10,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="The path/URL triggered when users click this country.",
                        max_length=500,
                        null=True,
                        verbose_name="Change Country URL / Path",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order Position"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is Visible"),
                ),
                (
                    "header_bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countries",
                        to="foundation.headerbar",
                        verbose_name="Header Bar Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Country",
                "verbose_name_plural": "Header Countries",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="HeaderCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Example: US Dollar",
                        max_length=50,
                        verbose_name="Currency Name / Label",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Example: USD",
                        max_length=10,
                        verbose_name="Currency Code",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        help_text="Example: $",
                        max_length=10,
                        null=True,
                        verbose_name="Currency Symbol",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="The path/URL triggered when users click this currency.",
                        max_length=500,
                        null=True,
                        verbose_name="Change Currency URL / Path",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order Position"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is Visible"),
                ),
                (
                    "header_bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currencies",
                        to="foundation.headerbar",
                        verbose_name="Header Bar Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Currency",
                "verbose_name_plural": "Header Currencies",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="HeaderLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Example: English",
                        max_length=50,
                        verbose_name="Language Name / Label",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Example: EN",
                        max_length=10,
                        verbose_name="Language Code",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="The path/URL triggered when users click this language.",
                        max_length=500,
                        null=True,
                        verbose_name="Change Language URL / Path",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order Position"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is Visible"),
                ),
                (
                    "header_bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="foundation.headerbar",
                        verbose_name="Header Bar Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Language",
                "verbose_name_plural": "Header Languages",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="HeaderUtilityLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "utility_type",
                    models.CharField(
                        choices=[
                            ("custom", "Custom Link"),
                            ("phone", "Phone Number"),
                            ("email", "Email Address"),
                            ("store_locator", "Store Locator"),
                            ("account", "Account Link"),
                        ],
                        default="custom",
                        help_text="Defines the semantic purpose of this link.",
                        max_length=20,
                        verbose_name="Utility Type",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=120, verbose_name="Link Label / Text"),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Link Target URL / Path",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("left", "Left Side"), ("right", "Right Side")],
                        default="left",
                        max_length=10,
                        verbose_name="Header Placement Side",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="Match keys like: phone, email, map-pin, truck, info.",
                        max_length=50,
                        null=True,
                        verbose_name="Icon Library Key",
                    ),
                ),
                (
                    "show_dropdown_icon",
                    models.BooleanField(
                        default=False,
                        help_text="Display a small down arrow next to the link text.",
                        verbose_name="Show Dropdown Caret",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order Position"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is Visible"),
                ),
                (
                    "header_bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilities",
                        to="foundation.headerbar",
                        verbose_name="Header Bar Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Utility Link",
                "verbose_name_plural": "Header Utility Links",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="NavbarMegaMenuColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        help_text="Optional heading displayed above the column links.",
                        max_length=120,
                        null=True,
                        verbose_name="Column Heading",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear further to the left.",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "visibility_scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all", "All Devices"),
                            ("desktop", "Desktop Only"),
                            ("mobile", "Mobile Only"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Visibility Scope",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "parent_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mega_menu_columns",
                        to="foundation.navbaritem",
                        verbose_name="Parent Navbar Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mega Menu Column",
                "verbose_name_plural": "Mega Menu Columns",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="NavbarMegaMenuLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=120, verbose_name="Link Label")),
                (
                    "link_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Link URL"
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Icon Key"
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(default=False, verbose_name="Open in New Tab"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Apply visual emphasis to this specific link.",
                        verbose_name="Is Featured",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear higher in the column.",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "visibility_scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all", "All Devices"),
                            ("desktop", "Desktop Only"),
                            ("mobile", "Mobile Only"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Visibility Scope",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "parent_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="foundation.navbarmegamenucolumn",
                        verbose_name="Parent Column",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mega Menu Link",
                "verbose_name_plural": "Mega Menu Links",
                "ordering": ["position", "id"],
            },
        ),
    ]
