# Generated by Django 5.1.4 on 2026-07-21 17:25

import apps.foundation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0002_contactpage_footerpaymentmethod_footersection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactemail",
            name="email_address",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="contactemail",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Is Visible"),
        ),
        migrations.AlterField(
            model_name="contactemail",
            name="label",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="Email Label/Department",
            ),
        ),
        migrations.AlterField(
            model_name="contactemail",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Display Order Position"
            ),
        ),
        migrations.AlterField(
            model_name="contactofficehour",
            name="closing_time",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Closing Time"
            ),
        ),
        migrations.AlterField(
            model_name="contactofficehour",
            name="day",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Day/Day Range"
            ),
        ),
        migrations.AlterField(
            model_name="contactofficehour",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Is Visible"),
        ),
        migrations.AlterField(
            model_name="contactofficehour",
            name="opening_time",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Opening Time"
            ),
        ),
        migrations.AlterField(
            model_name="contactofficehour",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Display Order Position"
            ),
        ),
        migrations.AlterField(
            model_name="contactofficehour",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("by_appointment", "By Appointment Only"),
                ],
                default="open",
                max_length=50,
                null=True,
                verbose_name="Operating Status",
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="address_heading",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Heading"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="form_heading",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Form Section Heading",
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="form_subheading",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Form Section Subheading",
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="form_submit_button_label",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="Form Submit Button Text",
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="form_success_message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Form Success Feedback Message"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="hero_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Hero Description"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.foundation.models._upload_to_contact_media,
                verbose_name="Hero Background Image",
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="hero_subtitle",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Hero Subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="hero_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Hero Title"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="hours_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Office Hours Description Text"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="intro_heading",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Intro Heading"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="intro_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Intro Description Text"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="map_embed_url",
            field=models.TextField(
                blank=True, null=True, verbose_name="Google Map Embed URL"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="physical_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Physical Address"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="seo_meta_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="SEO Meta Description"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="seo_meta_keywords",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SEO Meta Keywords"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="seo_meta_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SEO Meta Title"
            ),
        ),
        migrations.AlterField(
            model_name="contactphone",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Is Visible"),
        ),
        migrations.AlterField(
            model_name="contactphone",
            name="label",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="Phone Label/Department",
            ),
        ),
        migrations.AlterField(
            model_name="contactphone",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="contactphone",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Display Order Position"
            ),
        ),
        migrations.AlterField(
            model_name="contactsociallink",
            name="icon_class",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Icon CSS Class"
            ),
        ),
        migrations.AlterField(
            model_name="contactsociallink",
            name="icon_key",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Icon Library Key Lookup Reference",
            ),
        ),
        migrations.AlterField(
            model_name="contactsociallink",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Is Visible"),
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="action",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="Trigger Action ID Hook",
            ),
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="link_type",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Link Action Type System",
            ),
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Link Vertical Sort Index Position"
            ),
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="route",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Link Target Route / URL",
            ),
        ),
        migrations.AlterField(
            model_name="footerpaymentmethod",
            name="icon_key",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Icon Library Token Lookup Match",
            ),
        ),
        migrations.AlterField(
            model_name="footersection",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Display Order Position"
            ),
        ),
        migrations.AlterField(
            model_name="footersection",
            name="title",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="Section Column Title",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="brand_name",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Brand Name"
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="copyright_template",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Copyright Template"
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="fair_trade_statement",
            field=models.TextField(
                blank=True, null=True, verbose_name="Fair Trade / Trust Statement"
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="footer/", verbose_name="Footer Logo"
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="newsletter_endpoint",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Newsletter Submission Endpoint",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="newsletter_heading",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Newsletter Heading"
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="newsletter_placeholder",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="Newsletter Input Placeholder",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="newsletter_subtext",
            field=models.TextField(
                blank=True, null=True, verbose_name="Newsletter Subtext"
            ),
        ),
        migrations.AlterField(
            model_name="footersociallink",
            name="icon_class",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Icon CSS Class"
            ),
        ),
        migrations.AlterField(
            model_name="footersociallink",
            name="icon_key",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Icon Library Key Lookup Reference",
            ),
        ),
        migrations.AlterField(
            model_name="footersociallink",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Is Visible"),
        ),
        migrations.AlterField(
            model_name="footertrustbadge",
            name="icon_key",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Icon Library Vector ID Token Key",
            ),
        ),
        migrations.AlterField(
            model_name="headerannouncement",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Activation End Date"
            ),
        ),
        migrations.AlterField(
            model_name="headerannouncement",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Is Visible"),
        ),
        migrations.AlterField(
            model_name="headerannouncement",
            name="position",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Display Order Position"
            ),
        ),
        migrations.AlterField(
            model_name="headerannouncement",
            name="priority",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Priority Sequence"
            ),
        ),
        migrations.AlterField(
            model_name="headerannouncement",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Activation Start Date"
            ),
        ),
        migrations.AlterField(
            model_name="headerannouncement",
            name="text",
            field=models.CharField(max_length=255, verbose_name="Announcement Text"),
        ),
        migrations.AlterField(
            model_name="headerbar",
            name="announcement_messages",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Announcement Messages"
            ),
        ),
        migrations.AlterField(
            model_name="headerbar",
            name="currency_label",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Currency Label"
            ),
        ),
        migrations.AlterField(
            model_name="headerbar",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="Enable Header Bar"),
        ),
        migrations.AlterField(
            model_name="headerbar",
            name="is_sticky",
            field=models.BooleanField(default=False, verbose_name="Sticky Header Bar"),
        ),
        migrations.AlterField(
            model_name="headerbar",
            name="language_label",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Language Label"
            ),
        ),
        migrations.AlterField(
            model_name="headerbar",
            name="left_utilities",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Left Utility Items"
            ),
        ),
        migrations.AlterField(
            model_name="headerbar",
            name="right_utilities",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Right Utility Items"
            ),
        ),
        migrations.AlterField(
            model_name="headerbar",
            name="rotator_interval_ms",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Rotator Interval (ms)"
            ),
        ),
        migrations.AlterField(
            model_name="headercountry",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Country Code"),
        ),
        migrations.AlterField(
            model_name="headercountry",
            name="link_url",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Change Country URL / Path",
            ),
        ),
        migrations.AlterField(
            model_name="headercountry",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Country Name"),
        ),
        migrations.AlterField(
            model_name="headercurrency",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Currency Code"),
        ),
        migrations.AlterField(
            model_name="headercurrency",
            name="label",
            field=models.CharField(max_length=50, verbose_name="Currency Name / Label"),
        ),
        migrations.AlterField(
            model_name="headercurrency",
            name="link_url",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Change Currency URL / Path",
            ),
        ),
        migrations.AlterField(
            model_name="headercurrency",
            name="symbol",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Currency Symbol"
            ),
        ),
        migrations.AlterField(
            model_name="headerlanguage",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Language Code"),
        ),
        migrations.AlterField(
            model_name="headerlanguage",
            name="label",
            field=models.CharField(max_length=50, verbose_name="Language Name / Label"),
        ),
        migrations.AlterField(
            model_name="headerlanguage",
            name="link_url",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Change Language URL / Path",
            ),
        ),
        migrations.AlterField(
            model_name="headerutilitylink",
            name="icon_key",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Icon Library Key"
            ),
        ),
        migrations.AlterField(
            model_name="headerutilitylink",
            name="show_dropdown_icon",
            field=models.BooleanField(
                default=False, verbose_name="Show Dropdown Caret"
            ),
        ),
        migrations.AlterField(
            model_name="headerutilitylink",
            name="utility_type",
            field=models.CharField(
                choices=[
                    ("custom", "Custom Link"),
                    ("phone", "Phone Number"),
                    ("email", "Email Address"),
                    ("store_locator", "Store Locator"),
                    ("account", "Account Link"),
                ],
                default="custom",
                max_length=20,
                verbose_name="Utility Type",
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="badge_style",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Badge Style"
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="badge_text",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Badge Text"
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="featured_cta_text",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Featured CTA Text"
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="featured_cta_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Featured CTA URL"
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="featured_end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Featured Media End Date"
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.foundation.models._upload_to_navbar_media,
                verbose_name="Featured Image",
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="featured_start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Featured Media Start Date"
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="icon_key",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Icon Key"
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="label",
            field=models.CharField(max_length=120, verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="link_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Link URL"
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="menu_type",
            field=models.CharField(
                choices=[
                    ("link", "Link"),
                    ("dropdown", "Dropdown"),
                    ("mega_menu", "Mega Menu"),
                ],
                max_length=20,
                verbose_name="Menu Type",
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="foundation.navbaritem",
                verbose_name="Parent Item",
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Display Order"
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="requires_authentication",
            field=models.BooleanField(
                default=False, verbose_name="Requires Authentication"
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=120, null=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="visibility_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "All Devices"),
                    ("desktop", "Desktop Only"),
                    ("mobile", "Mobile Only"),
                ],
                max_length=20,
                null=True,
                verbose_name="Visibility Scope",
            ),
        ),
        migrations.AlterField(
            model_name="navbarmegamenucolumn",
            name="heading",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Column Heading"
            ),
        ),
        migrations.AlterField(
            model_name="navbarmegamenucolumn",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Display Order"),
        ),
        migrations.AlterField(
            model_name="navbarmegamenulink",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Is Featured"),
        ),
        migrations.AlterField(
            model_name="navbarmegamenulink",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Display Order"),
        ),
        migrations.AlterField(
            model_name="navbarsettings",
            name="is_sticky",
            field=models.BooleanField(default=True, verbose_name="Sticky Navigation"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="cart_badge_count",
            field=models.PositiveIntegerField(
                blank=True, default=2, null=True, verbose_name="Cart Badge Count"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="cart_button_label",
            field=models.CharField(
                blank=True,
                default="Shopping Bag",
                max_length=120,
                null=True,
                verbose_name="Cart Button Label",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="default_featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.foundation.models._upload_to_navbar_media,
                verbose_name="Default Mega Menu Featured Image",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="default_featured_text",
            field=models.TextField(
                blank=True,
                default="Explore the workshop lineages of India.",
                null=True,
                verbose_name="Default Mega Menu Featured Text",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="default_featured_title",
            field=models.CharField(
                blank=True,
                default="Meet the Artisans",
                max_length=160,
                null=True,
                verbose_name="Default Mega Menu Featured Title",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="enable_customer_registration",
            field=models.BooleanField(
                default=True, verbose_name="Enable Customer Registration"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="enable_facebook_login",
            field=models.BooleanField(
                default=True, verbose_name="Enable Facebook Login"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="enable_github_login",
            field=models.BooleanField(
                default=False, verbose_name="Enable GitHub Login"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="enable_google_login",
            field=models.BooleanField(default=True, verbose_name="Enable Google Login"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="enable_guest_checkout",
            field=models.BooleanField(
                default=True, verbose_name="Enable Guest Checkout"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="enable_social_login",
            field=models.BooleanField(default=True, verbose_name="Enable Social Login"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                help_text="Mandatory site logo upload.",
                upload_to=apps.foundation.models._upload_to_site_logo,
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_link",
            field=models.CharField(
                blank=True,
                default="/",
                max_length=500,
                null=True,
                verbose_name="Logo Link URL",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="search_button_label",
            field=models.CharField(
                blank=True,
                default="Search",
                max_length=120,
                null=True,
                verbose_name="Search Button Label",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="search_placeholder",
            field=models.CharField(
                blank=True,
                default="Find artisan rugs...",
                max_length=255,
                null=True,
                verbose_name="Search Placeholder",
            ),
        ),
    ]
