# Generated by Django 5.1.4 on 2026-06-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "foundation",
            "0002_footerpaymentmethod_footersection_footersettings_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional logo image dedicated to the footer section.",
                null=True,
                upload_to="footer/",
                verbose_name="Footer Logo",
            ),
        ),
    ]
