# Generated by Django 5.1.4 on 2026-07-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0003_alter_contactemail_email_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="company_notification_email",
            field=models.EmailField(
                blank=True,
                default="admin@gobindashandicrafts.com",
                help_text="Email address where new registration alerts and order notifications are delivered.",
                max_length=254,
                null=True,
                verbose_name="Company / Owner Notification Email ID",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="sender_display_name",
            field=models.CharField(
                blank=True,
                default="Gobindas Handicrafts",
                help_text="Friendly sender name displayed in customer inboxes.",
                max_length=120,
                null=True,
                verbose_name="Sender Display Name",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="sender_email_address",
            field=models.EmailField(
                blank=True,
                default="noreply@gobindashandicrafts.com",
                help_text="Automated 'From' email address used for customer communications.",
                max_length=254,
                null=True,
                verbose_name="System Sender Email Address (From)",
            ),
        ),
    ]
