# Generated by Django 5.1.4 on 2026-06-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0003_footersettings_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeaderAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "text",
                    models.CharField(
                        help_text="Message text shown in the announcement rotator.",
                        max_length=255,
                        verbose_name="Announcement Text",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers display first.",
                        verbose_name="Display Order Position",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Control if this announcement is active and visible.",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "header_bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="foundation.headerbar",
                        verbose_name="Header Bar Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Announcement",
                "verbose_name_plural": "Header Announcements",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="HeaderCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Example: US Dollar",
                        max_length=50,
                        verbose_name="Currency Name / Label",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Example: USD",
                        max_length=10,
                        verbose_name="Currency Code",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        help_text="Example: $",
                        max_length=10,
                        null=True,
                        verbose_name="Currency Symbol",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="The path/URL triggered when users click this currency.",
                        max_length=500,
                        null=True,
                        verbose_name="Change Currency URL / Path",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order Position"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is Visible"),
                ),
                (
                    "header_bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currencies",
                        to="foundation.headerbar",
                        verbose_name="Header Bar Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Currency",
                "verbose_name_plural": "Header Currencies",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="HeaderLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Example: English",
                        max_length=50,
                        verbose_name="Language Name / Label",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Example: EN",
                        max_length=10,
                        verbose_name="Language Code",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="The path/URL triggered when users click this language.",
                        max_length=500,
                        null=True,
                        verbose_name="Change Language URL / Path",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order Position"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is Visible"),
                ),
                (
                    "header_bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="foundation.headerbar",
                        verbose_name="Header Bar Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Language",
                "verbose_name_plural": "Header Languages",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="HeaderUtilityLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(max_length=120, verbose_name="Link Label / Text"),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Link Target URL / Path",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("left", "Left Side"), ("right", "Right Side")],
                        default="left",
                        max_length=10,
                        verbose_name="Header Placement Side",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="Match keys like: phone, email, map-pin, truck, info.",
                        max_length=50,
                        null=True,
                        verbose_name="Icon Library Key",
                    ),
                ),
                (
                    "show_dropdown_icon",
                    models.BooleanField(
                        default=False,
                        help_text="Display a small down arrow next to the link text.",
                        verbose_name="Show Dropdown Caret",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order Position"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is Visible"),
                ),
                (
                    "header_bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilities",
                        to="foundation.headerbar",
                        verbose_name="Header Bar Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Utility Link",
                "verbose_name_plural": "Header Utility Links",
                "ordering": ["position", "id"],
            },
        ),
    ]
