# Generated by Django 5.1.4 on 2026-07-27 16:29

import apps.foundation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0004_sitesettings_company_notification_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalBusinessCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Full Name"),
                ),
                (
                    "title_or_role",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Title / Designation",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Gobindas Handicrafts",
                        max_length=200,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL identifier (e.g., 'rajesh-shrestha')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.foundation.models._upload_to_card_avatars,
                        verbose_name="Profile Photo / Company Logo",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="WhatsApp Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website URL"),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Physical Address"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, null=True, verbose_name="Short Bio / Description"
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, null=True, verbose_name="Facebook URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Instagram URL"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.foundation.models._upload_to_qr_codes,
                        verbose_name="Generated QR Code PNG",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Card Active"),
                ),
            ],
            options={
                "verbose_name": "Digital Business Card",
                "verbose_name_plural": "Digital Business Cards",
                "ordering": ["full_name"],
            },
        ),
    ]
