# Generated by Django 5.1.4 on 2026-06-26 17:26

import apps.foundation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "foundation",
            "0004_headerannouncement_headercurrency_headerlanguage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="cart_badge_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=2,
                help_text="Dynamic count badge shown on the header cart button.",
                null=True,
                verbose_name="Cart Badge Count",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cart_button_label",
            field=models.CharField(
                blank=True,
                default="Shopping Bag",
                help_text="Accessibility label/text for the cart button.",
                max_length=120,
                null=True,
                verbose_name="Cart Button Label",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Fallback featured image for mega menus when no specific image is provided.",
                null=True,
                upload_to=apps.foundation.models._upload_to_navbar_media,
                verbose_name="Default Mega Menu Featured Image",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_featured_text",
            field=models.TextField(
                blank=True,
                default="Explore the workshop lineages of India.",
                help_text="Fallback featured description text for mega menus.",
                null=True,
                verbose_name="Default Mega Menu Featured Text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_featured_title",
            field=models.CharField(
                blank=True,
                default="Meet the Artisans",
                help_text="Fallback featured title for mega menus.",
                max_length=160,
                null=True,
                verbose_name="Default Mega Menu Featured Title",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="search_button_label",
            field=models.CharField(
                blank=True,
                default="Search",
                help_text="Accessibility label/text for the search button.",
                max_length=120,
                null=True,
                verbose_name="Search Button Label",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="search_placeholder",
            field=models.CharField(
                blank=True,
                default="Find artisan rugs...",
                help_text="Placeholder text shown inside the global header search input.",
                max_length=255,
                null=True,
                verbose_name="Search Placeholder",
            ),
        ),
    ]
