# Generated by Django 5.1.4 on 2026-06-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0005_sitesettings_cart_badge_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navbaritem",
            name="mega_menu_columns",
        ),
        migrations.CreateModel(
            name="NavbarMegaMenuColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        help_text="Optional heading displayed above the column links.",
                        max_length=120,
                        null=True,
                        verbose_name="Column Heading",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear further to the left.",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "parent_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mega_menu_columns",
                        to="foundation.navbaritem",
                        verbose_name="Parent Navbar Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mega Menu Column",
                "verbose_name_plural": "Mega Menu Columns",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="NavbarMegaMenuLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=120, verbose_name="Link Label")),
                (
                    "link_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Link URL"
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(default=False, verbose_name="Open in New Tab"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear higher in the column.",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "parent_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="foundation.navbarmegamenucolumn",
                        verbose_name="Parent Column",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mega Menu Link",
                "verbose_name_plural": "Mega Menu Links",
                "ordering": ["position", "id"],
            },
        ),
    ]
