# Generated by Django 5.1.4 on 2026-07-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0006_remove_navbaritem_mega_menu_columns_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="enable_customer_registration",
            field=models.BooleanField(
                default=True,
                help_text="Globally enable or disable new customer account registration pages and buttons.",
                verbose_name="Enable Customer Registration",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_facebook_login",
            field=models.BooleanField(
                default=True,
                help_text="Allow customers to log in using their Facebook accounts (if Social Login is enabled).",
                verbose_name="Enable Facebook Login",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_github_login",
            field=models.BooleanField(
                default=False,
                help_text="Allow customers to log in using their GitHub accounts (if Social Login is enabled).",
                verbose_name="Enable GitHub Login",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_google_login",
            field=models.BooleanField(
                default=True,
                help_text="Allow customers to log in using their Google accounts (if Social Login is enabled).",
                verbose_name="Enable Google Login",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_guest_checkout",
            field=models.BooleanField(
                default=True,
                help_text="Globally allow or restrict customers from checking out without creating an account.",
                verbose_name="Enable Guest Checkout",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_social_login",
            field=models.BooleanField(
                default=True,
                help_text="Globally enable or disable social authentication (SSO) flows.",
                verbose_name="Enable Social Login",
            ),
        ),
    ]
