# Generated by Django 5.1.4 on 2026-07-01 04:58

import apps.foundation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0007_sitesettings_enable_customer_registration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavbarSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Enable Main Navigation"
                    ),
                ),
                (
                    "is_sticky",
                    models.BooleanField(
                        default=True,
                        help_text="Keep navigation pinned to top while scrolling.",
                        verbose_name="Sticky Navigation",
                    ),
                ),
                (
                    "desktop_behavior",
                    models.CharField(
                        choices=[
                            ("hover", "Open on Hover"),
                            ("click", "Open on Click"),
                        ],
                        default="hover",
                        max_length=50,
                        verbose_name="Desktop Navigation Behavior",
                    ),
                ),
                (
                    "mobile_behavior",
                    models.CharField(
                        choices=[
                            ("accordion", "Accordion Menu"),
                            ("offcanvas", "Offcanvas Menu"),
                        ],
                        default="offcanvas",
                        max_length=50,
                        verbose_name="Mobile Navigation Behavior",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navbar Settings",
                "verbose_name_plural": "Navbar Settings",
            },
        ),
        migrations.AddField(
            model_name="headerannouncement",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when this announcement should stop displaying.",
                null=True,
                verbose_name="Activation End Date",
            ),
        ),
        migrations.AddField(
            model_name="headerannouncement",
            name="priority",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Higher numbers take precedence if multiple announcements overlap.",
                verbose_name="Priority Sequence",
            ),
        ),
        migrations.AddField(
            model_name="headerannouncement",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when this announcement should start displaying.",
                null=True,
                verbose_name="Activation Start Date",
            ),
        ),
        migrations.AddField(
            model_name="headerbar",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Globally toggle the visibility of the entire top header bar.",
                verbose_name="Enable Header Bar",
            ),
        ),
        migrations.AddField(
            model_name="headerbar",
            name="is_sticky",
            field=models.BooleanField(
                default=False,
                help_text="Pin the header bar to the top of the viewport when scrolling.",
                verbose_name="Sticky Header Bar",
            ),
        ),
        migrations.AddField(
            model_name="headerbar",
            name="show_on_desktop",
            field=models.BooleanField(
                default=True, verbose_name="Show on Desktop Devices"
            ),
        ),
        migrations.AddField(
            model_name="headerbar",
            name="show_on_mobile",
            field=models.BooleanField(
                default=True, verbose_name="Show on Mobile Devices"
            ),
        ),
        migrations.AddField(
            model_name="headerutilitylink",
            name="utility_type",
            field=models.CharField(
                choices=[
                    ("custom", "Custom Link"),
                    ("phone", "Phone Number"),
                    ("email", "Email Address"),
                    ("store_locator", "Store Locator"),
                    ("account", "Account Link"),
                ],
                default="custom",
                help_text="Defines the semantic purpose of this link.",
                max_length=20,
                verbose_name="Utility Type",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Activation End Date"
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="featured_cta_text",
            field=models.CharField(
                blank=True,
                help_text="Button text for the featured media block.",
                max_length=120,
                null=True,
                verbose_name="Featured CTA Text",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="featured_cta_url",
            field=models.CharField(
                blank=True,
                help_text="Button URL target for the featured media block.",
                max_length=500,
                null=True,
                verbose_name="Featured CTA URL",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="featured_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule when to stop showing the featured block.",
                null=True,
                verbose_name="Featured Media End Date",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="featured_is_visible",
            field=models.BooleanField(
                default=True, verbose_name="Featured Media Block Visibility"
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="featured_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule when to start showing the featured block.",
                null=True,
                verbose_name="Featured Media Start Date",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="icon_key",
            field=models.CharField(
                blank=True,
                help_text="Optional icon identifier for display next to label.",
                max_length=50,
                null=True,
                verbose_name="Icon Key",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="open_in_new_tab",
            field=models.BooleanField(default=False, verbose_name="Open in New Tab"),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="requires_authentication",
            field=models.BooleanField(
                default=False,
                help_text="If checked, item is only visible to logged-in users.",
                verbose_name="Requires Authentication",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Optional identifier for referencing within codebase.",
                max_length=120,
                null=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AddField(
            model_name="navbaritem",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Activation Start Date"
            ),
        ),
        migrations.AddField(
            model_name="navbarmegamenucolumn",
            name="visibility_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "All Devices"),
                    ("desktop", "Desktop Only"),
                    ("mobile", "Mobile Only"),
                ],
                max_length=20,
                null=True,
                verbose_name="Visibility Scope",
            ),
        ),
        migrations.AddField(
            model_name="navbarmegamenulink",
            name="icon_key",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Icon Key"
            ),
        ),
        migrations.AddField(
            model_name="navbarmegamenulink",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Apply visual emphasis to this specific link.",
                verbose_name="Is Featured",
            ),
        ),
        migrations.AddField(
            model_name="navbarmegamenulink",
            name="visibility_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "All Devices"),
                    ("desktop", "Desktop Only"),
                    ("mobile", "Mobile Only"),
                ],
                max_length=20,
                null=True,
                verbose_name="Visibility Scope",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_link",
            field=models.CharField(
                blank=True,
                default="/",
                help_text="The destination URL when the brand logo is clicked.",
                max_length=500,
                null=True,
                verbose_name="Logo Link URL",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mobile_logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional separate logo optimized for mobile devices.",
                null=True,
                upload_to=apps.foundation.models._upload_to_site_logo,
                verbose_name="Mobile Logo",
            ),
        ),
        migrations.CreateModel(
            name="HeaderCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Example: United States",
                        max_length=100,
                        verbose_name="Country Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Example: US",
                        max_length=10,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="The path/URL triggered when users click this country.",
                        max_length=500,
                        null=True,
                        verbose_name="Change Country URL / Path",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order Position"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is Visible"),
                ),
                (
                    "header_bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countries",
                        to="foundation.headerbar",
                        verbose_name="Header Bar Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Country",
                "verbose_name_plural": "Header Countries",
                "ordering": ["position", "id"],
            },
        ),
    ]
