# Generated by Django 5.1.4 on 2026-07-04 12:17

import apps.foundation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0008_navbarsettings_headerannouncement_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hero_title",
                    models.CharField(
                        blank=True,
                        help_text="Main heading displayed in the hero banner of the Contact Page.",
                        max_length=255,
                        null=True,
                        verbose_name="Hero Title",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Supporting subtitle text below the hero title.",
                        max_length=255,
                        null=True,
                        verbose_name="Hero Subtitle",
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        blank=True,
                        help_text="Paragraph description shown in the hero section.",
                        null=True,
                        verbose_name="Hero Description",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional large background/featured image for the contact page hero banner.",
                        null=True,
                        upload_to=apps.foundation.models._upload_to_contact_media,
                        verbose_name="Hero Background Image",
                    ),
                ),
                (
                    "intro_heading",
                    models.CharField(
                        blank=True,
                        help_text="Main intro title displayed prior to physical and communication details.",
                        max_length=255,
                        null=True,
                        verbose_name="Intro Heading",
                    ),
                ),
                (
                    "intro_text",
                    models.TextField(
                        blank=True,
                        help_text="Brief general contact text block.",
                        null=True,
                        verbose_name="Intro Description Text",
                    ),
                ),
                (
                    "address_heading",
                    models.CharField(
                        blank=True,
                        help_text="Heading label for the physical location section.",
                        max_length=255,
                        null=True,
                        verbose_name="Address Heading",
                    ),
                ),
                (
                    "physical_address",
                    models.TextField(
                        blank=True,
                        help_text="Multi-line physical location address text.",
                        null=True,
                        verbose_name="Physical Address",
                    ),
                ),
                (
                    "map_heading",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Map Section Heading",
                    ),
                ),
                (
                    "map_embed_url",
                    models.TextField(
                        blank=True,
                        help_text="Standard iframe source URL containing the customized embedded location link.",
                        null=True,
                        verbose_name="Google Map Embed URL",
                    ),
                ),
                (
                    "hours_heading",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Office Hours Heading",
                    ),
                ),
                (
                    "hours_description",
                    models.TextField(
                        blank=True,
                        help_text="Supporting caption details under the office hours heading.",
                        null=True,
                        verbose_name="Office Hours Description Text",
                    ),
                ),
                (
                    "form_heading",
                    models.CharField(
                        blank=True,
                        help_text="Header layout title displayed above the interactive submission form.",
                        max_length=255,
                        null=True,
                        verbose_name="Form Section Heading",
                    ),
                ),
                (
                    "form_subheading",
                    models.CharField(
                        blank=True,
                        help_text="Brief subtitle or prompt guiding user input.",
                        max_length=255,
                        null=True,
                        verbose_name="Form Section Subheading",
                    ),
                ),
                (
                    "form_submit_button_label",
                    models.CharField(
                        blank=True,
                        help_text="Clickable submission action button text value.",
                        max_length=120,
                        null=True,
                        verbose_name="Form Submit Button Text",
                    ),
                ),
                (
                    "form_success_message",
                    models.TextField(
                        blank=True,
                        help_text="Popup or banner alert text appearing upon successful verification submissions.",
                        null=True,
                        verbose_name="Form Success Feedback Message",
                    ),
                ),
                (
                    "seo_meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Custom title tag optimized specifically for search engines.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Meta Title",
                    ),
                ),
                (
                    "seo_meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Search engine index description text snippets.",
                        null=True,
                        verbose_name="SEO Meta Description",
                    ),
                ),
                (
                    "seo_meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords mapping search engine priority references.",
                        max_length=255,
                        null=True,
                        verbose_name="SEO Meta Keywords",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Page Settings",
                "verbose_name_plural": "Contact Page Settings",
            },
        ),
        migrations.CreateModel(
            name="ContactOfficeHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Monday, Monday - Friday, Weekends",
                        max_length=120,
                        null=True,
                        verbose_name="Day/Day Range",
                    ),
                ),
                (
                    "opening_time",
                    models.CharField(
                        blank=True,
                        help_text="Custom time format string (e.g., '9:00 AM', '09:00').",
                        max_length=120,
                        null=True,
                        verbose_name="Opening Time",
                    ),
                ),
                (
                    "closing_time",
                    models.CharField(
                        blank=True,
                        help_text="Custom time format string (e.g., '5:00 PM', '17:00').",
                        max_length=120,
                        null=True,
                        verbose_name="Closing Time",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("by_appointment", "By Appointment Only"),
                        ],
                        default="open",
                        help_text="System state for the scheduled timeframe display.",
                        max_length=50,
                        null=True,
                        verbose_name="Operating Status",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ascending sort position order values controlling tabular render ranking.",
                        null=True,
                        verbose_name="Display Order Position",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle operating schedule visibility.",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "contact_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_hours",
                        to="foundation.contactpage",
                        verbose_name="Parent Contact Page Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Office Hour",
                "verbose_name_plural": "Contact Office Hours",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Customer Care, Press/PR",
                        max_length=120,
                        null=True,
                        verbose_name="Email Label/Department",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Valid email reference target destination.",
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Lower numeric positions dictate vertical sort priority ranking.",
                        null=True,
                        verbose_name="Display Order Position",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Control if this email entry is visible on the frontend page.",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "contact_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="foundation.contactpage",
                        verbose_name="Parent Contact Page Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Email",
                "verbose_name_plural": "Contact Emails",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="e.g., General Inquiries, Technical Support",
                        max_length=120,
                        null=True,
                        verbose_name="Phone Label/Department",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Callable phone number value.",
                        max_length=50,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Lower numeric positions dictate vertical sort priority ranking.",
                        null=True,
                        verbose_name="Display Order Position",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Control if this phone entry is visible on the frontend page.",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "contact_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="foundation.contactpage",
                        verbose_name="Parent Contact Page Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Phone",
                "verbose_name_plural": "Contact Phones",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Platform Name",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Profile URL Destination Path",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="System programmatic token to map vector icon assets (e.g., 'instagram', 'pinterest').",
                        max_length=50,
                        null=True,
                        verbose_name="Icon Library Key Lookup Reference",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Display Order Position"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Control if this social link is active and visible.",
                        verbose_name="Is Visible",
                    ),
                ),
                (
                    "contact_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="foundation.contactpage",
                        verbose_name="Parent Contact Page Settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Social Link",
                "verbose_name_plural": "Contact Social Links",
                "ordering": ["position", "id"],
            },
        ),
    ]
