# Generated by Django 5.1.4 on 2026-07-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0009_contactpage_contactofficehour_contactemail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsociallink",
            name="icon_class",
            field=models.CharField(
                blank=True,
                help_text="CSS class for the icon (e.g., 'fab fa-facebook-f'). Allows dynamic config without code changes.",
                max_length=255,
                null=True,
                verbose_name="Icon CSS Class",
            ),
        ),
        migrations.AddField(
            model_name="footersociallink",
            name="icon_class",
            field=models.CharField(
                blank=True,
                help_text="CSS class for the icon (e.g., 'fab fa-facebook-f'). Allows dynamic config without code changes.",
                max_length=255,
                null=True,
                verbose_name="Icon CSS Class",
            ),
        ),
        migrations.AddField(
            model_name="footersociallink",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="Control if this social link is active and visible.",
                verbose_name="Is Visible",
            ),
        ),
    ]
