# Generated by Django 5.1.4 on 2026-07-16 05:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Display name of the warehouse / fulfillment center.",
                        max_length=150,
                        null=True,
                        verbose_name="Warehouse Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Unique short code used in references and reports (e.g. 'KTM-01'). Auto-uppercased on save.",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Warehouse Code",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Free-form location description (city, district, etc.).",
                        max_length=255,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 7-20 characters and may only contain digits, spaces, hyphens, parentheses, and an optional leading +.",
                                regex="^\\+?[0-9\\s\\-\\(\\)]{7,20}$",
                            )
                        ],
                        verbose_name="Phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=False,
                        help_text="Designates this warehouse as the primary automatic fulfillment source. Only one active default warehouse is supported at a time.",
                        null=True,
                        verbose_name="Is Default Warehouse",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=True,
                        help_text="Soft deactivation flag. Inactive warehouses are hidden from selection UIs.",
                        null=True,
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "db_table": "inventory_warehouse",
                "ordering": ["-is_default", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "available_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current sellable stock. Never negative.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Available Quantity",
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Stock currently held in active reservations (carts, holds, etc.).",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Reserved Quantity",
                    ),
                ),
                (
                    "damaged_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Stock removed from sale due to damage. Tracked separately for accounting.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Damaged Quantity",
                    ),
                ),
                (
                    "incoming_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Stock expected from suppliers / POs in transit.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Incoming Quantity",
                    ),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Low-stock alert threshold.",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Minimum Stock Level",
                    ),
                ),
                (
                    "maximum_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Storage capacity ceiling for this warehouse.",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Maximum Stock Level",
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="When available stock falls to or below this level, replenishment should be initiated.",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Reorder Level",
                    ),
                ),
                (
                    "location_bin",
                    models.CharField(
                        blank=True,
                        help_text="Physical location inside the warehouse (rack/shelf/bin code).",
                        max_length=120,
                        null=True,
                        verbose_name="Location Bin",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=True,
                        null=True,
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product for which stock is tracked (when no variant is selected).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_records",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Variant for which stock is tracked. NULL for product-level stock.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_records",
                        to="catalog.productvariant",
                        verbose_name="Product Variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory",
                "verbose_name_plural": "Inventory Records",
                "db_table": "inventory_inventory",
                "ordering": ["warehouse", "product_variant", "product", "id"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase / Receiving"),
                            ("sale", "Sale / Fulfillment"),
                            ("return", "Customer Return"),
                            ("cancel", "Order Cancellation"),
                            ("transfer", "Warehouse Transfer"),
                            ("damage", "Damaged / Write-off"),
                            ("adjustment", "Manual Adjustment"),
                            ("opening", "Opening Balance"),
                            ("recount", "Physical Recount"),
                            ("reservation_release", "Reservation Release"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound (+)"),
                            ("outbound", "Outbound (−)"),
                            ("neutral", "Neutral (no quantity change)"),
                        ],
                        db_index=True,
                        default="neutral",
                        help_text="Whether the transaction increases (+) or decreases (-) available stock. Derived from transaction_type at the service layer.",
                        max_length=16,
                        verbose_name="Flow Direction",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Quantity moved. Direction is recorded separately in 'direction'.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "available_before",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Snapshot of available_quantity immediately before this transaction.",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Available Quantity Before",
                    ),
                ),
                (
                    "available_after",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Snapshot of available_quantity immediately after this transaction.",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Available Quantity After",
                    ),
                ),
                (
                    "reserved_before",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Reserved Quantity Before",
                    ),
                ),
                (
                    "reserved_after",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Reserved Quantity After",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Per-unit cost at the time of this transaction. Used for COGS calculations.",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-computed: quantity × unit_cost. Stored for fast reporting.",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Total Cost",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default="NPR",
                        help_text="ISO 4217 currency code for the unit_cost and total_cost.",
                        max_length=10,
                        null=True,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="External reference number (PO, GRN, Order #, Return RMA, etc.).",
                        max_length=120,
                        null=True,
                        verbose_name="Reference Number",
                    ),
                ),
                (
                    "reference_model",
                    models.CharField(
                        blank=True,
                        help_text="App label and model name of the referenced record (e.g. 'orders.Order', 'purchases.PurchaseOrder').",
                        max_length=80,
                        null=True,
                        verbose_name="Reference Model",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the referenced record's primary key.",
                        max_length=80,
                        null=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "transfer_group_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Pairs the outbound and inbound transactions of a single transfer. Auto-generated on first save.",
                        verbose_name="Transfer Group ID",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="Remarks"),
                ),
                (
                    "transaction_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the stock movement physically occurred. Defaults to record creation time.",
                        verbose_name="Transaction Timestamp",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="inventory.inventory",
                        verbose_name="Inventory Record",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Transaction",
                "verbose_name_plural": "Inventory Transactions",
                "db_table": "inventory_transaction",
                "ordering": ["-transaction_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adjustment_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-generated audit reference. Format: ADJ-YYMMDD-XXXX. Generated automatically on first save.",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Adjustment Number",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("cycle_count", "Cycle Count"),
                            ("damage_writeoff", "Damage Write-off"),
                            ("found_stock", "Found Stock"),
                            ("lost_stock", "Lost Stock"),
                            ("supplier_correction", "Supplier Correction"),
                            ("system_reconciliation", "System Reconciliation"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=32,
                        verbose_name="Reason",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the adjustment context (counted, found, lost, etc.).",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "supporting_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='JSON list of supporting document references (URLs, photos, PDFs, etc.). Example: [{"url": "...", "type": "photo"}]',
                        verbose_name="Supporting Documents",
                    ),
                ),
                (
                    "old_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Snapshot of available_quantity at the time the adjustment was drafted.",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Old Quantity (Available)",
                    ),
                ),
                (
                    "new_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Desired new value of available_quantity after this adjustment is applied.",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="New Quantity (Available)",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-computed: new_quantity - old_quantity. May be negative.",
                        max_digits=14,
                        null=True,
                        verbose_name="Difference",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("applied", "Applied"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rejected At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Rejection Reason"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the adjustment was committed to inventory (and the InventoryTransaction was created).",
                        null=True,
                        verbose_name="Applied At",
                    ),
                ),
                (
                    "applied_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The InventoryTransaction that was created when this adjustment was applied.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="originating_adjustment",
                        to="inventory.inventorytransaction",
                        verbose_name="Applied Transaction",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_stock_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_stock_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Initiated By",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="inventory.inventory",
                        verbose_name="Inventory Record",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_stock_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Rejected By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Adjustment",
                "verbose_name_plural": "Stock Adjustments",
                "db_table": "inventory_stock_adjustment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation_token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique opaque identifier for external / API references.",
                        unique=True,
                        verbose_name="Reservation Token",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "reservation_type",
                    models.CharField(
                        choices=[
                            ("cart", "Cart"),
                            ("manual_hold", "Manual Hold"),
                            ("promotional", "Promotional Reservation"),
                            ("backorder", "Backorder"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="cart",
                        max_length=24,
                        verbose_name="Reservation Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("converted", "Converted to Order"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=True,
                        help_text="Quick boolean for the cron cleanup filter. Mirrors status == ACTIVE.",
                        null=True,
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this reservation automatically becomes eligible for cleanup.",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Released At"
                    ),
                ),
                (
                    "converted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Converted At"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="For anonymous carts - the session key owning this reservation.",
                        max_length=64,
                        null=True,
                        verbose_name="Session Key",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source cart. May be NULL for manual holds or anonymous API holds.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_reservations",
                        to="cart.cart",
                        verbose_name="Cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Reservation",
                "verbose_name_plural": "Stock Reservations",
                "db_table": "inventory_stock_reservation",
                "ordering": ["-created_at"],
            },
        ),
    ]
