# Generated by Django 5.1.4 on 2026-07-16 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("inventory", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockreservation",
            name="converted_to_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="originating_reservations",
                to="orders.order",
                verbose_name="Converted To Order",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific inventory row being reserved. Resolved automatically by the service layer if left blank.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="inventory.inventory",
                verbose_name="Inventory",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Used when no variant is selected.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_reservations",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_reservations",
                to="catalog.productvariant",
                verbose_name="Product Variant",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated user owning this reservation. NULL for anonymous carts.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["is_active"], name="inventory_w_is_acti_3ddeac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["is_default"], name="inventory_w_is_defa_4b7615_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["is_active", "is_default"],
                name="inventory_w_is_acti_1eba05_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_default", True), _negated=True),
                    ("is_active", True),
                    _connector="OR",
                ),
                name="warehouse_default_must_be_active",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Warehouse where the stock is reserved. Required if no inventory row is provided.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_reservations",
                to="inventory.warehouse",
                verbose_name="Warehouse",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="destination_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="For TRANSFER transactions: the warehouse receiving the stock.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_transfers",
                to="inventory.warehouse",
                verbose_name="Destination Warehouse",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_records",
                to="inventory.warehouse",
                verbose_name="Warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["inventory", "-created_at"],
                name="inventory_s_invento_fc4b78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["status", "-created_at"], name="inventory_s_status_4bc8eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["reason", "-created_at"], name="inventory_s_reason_bf4527_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["approved_by", "-approved_at"],
                name="inventory_s_approve_fc76bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["initiated_by", "-created_at"],
                name="inventory_s_initiat_53a145_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["draft", "pending_approval", "rejected", "cancelled"],
                    ),
                    ("approved_by__isnull", False),
                    _connector="OR",
                ),
                name="stockadj_approved_requires_approver",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "applied"), _negated=True),
                    ("applied_at__isnull", False),
                    _connector="OR",
                ),
                name="stockadj_applied_requires_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "rejected"), _negated=True),
                    models.Q(
                        ("rejected_by__isnull", False), ("rejected_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="stockadj_rejected_requires_metadata",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["status", "expires_at"], name="inventory_s_status_728372_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["cart", "status"], name="inventory_s_cart_id_26d491_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["session_key", "status"], name="inventory_s_session_2e600d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["user", "status"], name="inventory_s_user_id_42675e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["inventory", "status"], name="inventory_s_invento_0a0c9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["product_variant", "status"],
                name="inventory_s_product_93117b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["product", "status"], name="inventory_s_product_b75a2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["is_active", "expires_at"],
                name="inventory_s_is_acti_016d2a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("product_variant__isnull", True), ("product__isnull", False)
                    ),
                    models.Q(
                        ("product_variant__isnull", False), ("product__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="reservation_must_have_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="reservation_quantity_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_active", False), ("status", "active"), _connector="OR"
                ),
                name="reservation_active_status_match",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["inventory", "-transaction_at"],
                name="inventory_t_invento_7fba50_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["transaction_type", "-transaction_at"],
                name="inventory_t_transac_c1f3db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["direction", "-transaction_at"],
                name="inventory_t_directi_d5ecfd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["reference_number"], name="inventory_t_referen_e16505_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["reference_model", "reference_id"],
                name="inventory_t_referen_4f9ffb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["transaction_at"], name="inventory_t_transac_5961e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["-created_at"], name="inventory_t_created_1dfc6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["transfer_group_id"], name="inventory_t_transfe_4d3d6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["performed_by", "-transaction_at"],
                name="inventory_t_perform_da6192_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="invtx_quantity_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_cost__isnull", True),
                    ("total_cost__gte", 0),
                    _connector="OR",
                ),
                name="invtx_total_cost_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["warehouse", "product_variant"],
                name="inventory_i_warehou_1b4273_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["warehouse", "product"], name="inventory_i_warehou_5a1f66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["is_active"], name="inventory_i_is_acti_05630a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["product_variant", "is_active"],
                name="inventory_i_product_47f33f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["product", "is_active"], name="inventory_i_product_70b72a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product_variant__isnull", False)),
                fields=("warehouse", "product_variant"),
                name="inventory_unique_variant_per_warehouse",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("product__isnull", False), ("product_variant__isnull", True)
                ),
                fields=("warehouse", "product"),
                name="inventory_unique_product_no_variant_per_warehouse",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("product_variant__isnull", True), ("product__isnull", False)
                    ),
                    models.Q(
                        ("product_variant__isnull", False), ("product__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="inventory_must_have_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("available_quantity__gte", 0)),
                name="inventory_available_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__gte", 0)),
                name="inventory_reserved_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("damaged_quantity__gte", 0)),
                name="inventory_damaged_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("incoming_quantity__gte", 0)),
                name="inventory_incoming_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reserved_quantity__lte", models.F("available_quantity"))
                ),
                name="inventory_reserved_lte_available",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimum_stock__isnull", True),
                    ("maximum_stock__isnull", True),
                    ("minimum_stock__lte", models.F("maximum_stock")),
                    _connector="OR",
                ),
                name="inventory_min_lte_max",
            ),
        ),
    ]
