# Generated by Django 5.1.4 on 2026-07-22 06:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_initial"),
        ("catalog", "0003_alter_artisan_region_and_more"),
        ("inventory", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="damaged_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Stock removed from sale due to damage.",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Damaged Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="incoming_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Stock expected from suppliers in transit.",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Incoming Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="location_bin",
            field=models.CharField(
                blank=True,
                help_text="Physical rack/shelf/bin code inside warehouse.",
                max_length=120,
                null=True,
                verbose_name="Location Bin",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="reorder_level",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Replenishment threshold.",
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Reorder Level",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="reserved_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Stock currently held in active reservations.",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Reserved Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="available_after",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Available Quantity After",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="available_before",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Available Quantity Before",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="currency",
            field=models.CharField(
                blank=True,
                default="NPR",
                max_length=10,
                null=True,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="destination_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_transfers",
                to="inventory.warehouse",
                verbose_name="Destination Warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="direction",
            field=models.CharField(
                choices=[
                    ("inbound", "Inbound (+)"),
                    ("outbound", "Outbound (−)"),
                    ("neutral", "Neutral (no quantity change)"),
                ],
                db_index=True,
                default="neutral",
                max_length=16,
                verbose_name="Flow Direction",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="reference_id",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Reference ID"
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="reference_model",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Reference Model"
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="reference_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=120,
                null=True,
                verbose_name="Reference Number",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Total Cost",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transaction_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Transaction Timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transfer_group_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Transfer Group ID",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Unit Cost",
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="adjustment_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Adjustment Number",
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="applied_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Applied At"
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="applied_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="originating_adjustment",
                to="inventory.inventorytransaction",
                verbose_name="Applied Transaction",
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="difference",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Difference",
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="new_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="New Quantity (Available)",
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="old_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Old Quantity (Available)",
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="supporting_documents",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Supporting Documents"
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_reservations",
                to="cart.cart",
                verbose_name="Cart",
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Expires At"
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="inventory.inventory",
                verbose_name="Inventory",
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="is_active",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=True,
                null=True,
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_reservations",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="reservation_token",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Reservation Token",
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="Session Key",
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_reservations",
                to="inventory.warehouse",
                verbose_name="Warehouse",
            ),
        ),
    ]
