# Generated by Django 5.1.4 on 2026-07-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_inventory_damaged_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="currency",
            field=models.CharField(
                blank=True,
                default="USD",
                max_length=10,
                null=True,
                verbose_name="Currency",
            ),
        ),
    ]
