# Generated by Django 5.1.4 on 2026-07-23 15:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_remove_couponusage_coupon_usage_discount_gte_0_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enable_shipping_calculation",
                    models.BooleanField(
                        default=True,
                        verbose_name="Enable Shipping Rate Calculation System-Wide",
                    ),
                ),
                (
                    "default_fallback_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("150.00"),
                        help_text="Applied if no matching zone or shipping method is configured.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Fallback Delivery Rate (NPR)",
                    ),
                ),
                (
                    "free_shipping_subtotal_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cart subtotal amount at which standard shipping becomes free storewide.",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Global Free Shipping Threshold (NPR)",
                    ),
                ),
                (
                    "default_weight_unit",
                    models.CharField(
                        default="kg", max_length=10, verbose_name="Default Weight Unit"
                    ),
                ),
                (
                    "origin_country_code",
                    models.CharField(
                        default="NP",
                        max_length=2,
                        verbose_name="Origin Country (ISO 2-letter)",
                    ),
                ),
                (
                    "origin_city",
                    models.CharField(
                        default="Kathmandu",
                        max_length=100,
                        verbose_name="Origin Dispatch City",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Engine Settings",
                "verbose_name_plural": "Shipping Engine Settings",
            },
        ),
        migrations.CreateModel(
            name="ShipmentTrackingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tracking_number",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Tracking Number",
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("nepal_post", "Nepal Post / EMS"),
                            ("dhl", "DHL Express International"),
                            ("fedex", "FedEx Express"),
                            ("ups", "UPS Worldwide"),
                            ("aramex", "Aramex Express"),
                            ("local_courier", "Local Kathmandu / Domestic Courier"),
                        ],
                        default="local_courier",
                        max_length=50,
                        verbose_name="Carrier",
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        default="In Transit",
                        max_length=100,
                        verbose_name="Current Status",
                    ),
                ),
                (
                    "status_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Status Details / Checkpoint Notes",
                    ),
                ),
                (
                    "estimated_delivery",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Estimated Delivery Time"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_tracking_records",
                        to="orders.order",
                        verbose_name="Associated Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Tracking Record",
                "verbose_name_plural": "Shipment Tracking Records",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Title (e.g. 'Nepal Kathmandu Valley', 'USA & Canada', 'EU Member States').",
                        max_length=120,
                        verbose_name="Zone Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier (e.g. ZONE_NP_KTM, ZONE_US_CA, ZONE_GLOBAL). Auto-uppercased.",
                        max_length=50,
                        unique=True,
                        verbose_name="Zone Code",
                    ),
                ),
                (
                    "countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON list of 2-letter ISO country codes (e.g. ['NP', 'US', 'DE']). Empty applies globally.",
                        verbose_name="Target Country ISO Codes",
                    ),
                ),
                (
                    "states_or_provinces",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional list of specific states or provinces (e.g. ['Bagmati', 'California']).",
                        verbose_name="Target States / Provinces",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Lower priority numbers execute first during location lookup.",
                        verbose_name="Matching Priority",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Zone",
                "verbose_name_plural": "Shipping Zones",
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="shipping_sh_code_b527f8_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="shipping_sh_priorit_0f93f1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Title shown to customers at checkout (e.g. 'Nepal Express Courier', 'DHL Worldwide').",
                        max_length=150,
                        verbose_name="Method Title",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code (e.g. KTM_STD, DHL_EXPRESS, LOCAL_PICKUP). Auto-uppercased.",
                        max_length=50,
                        unique=True,
                        verbose_name="Method Code",
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("nepal_post", "Nepal Post / EMS"),
                            ("dhl", "DHL Express International"),
                            ("fedex", "FedEx Express"),
                            ("ups", "UPS Worldwide"),
                            ("aramex", "Aramex Express"),
                            ("local_courier", "Local Kathmandu / Domestic Courier"),
                        ],
                        default="local_courier",
                        max_length=50,
                        verbose_name="Delivery Carrier",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("flat_rate", "Flat Rate Shipping"),
                            ("weight_based", "Weight-Based Calculation"),
                            ("price_based", "Order Subtotal-Based Calculation"),
                            ("free_shipping", "Free Shipping Threshold"),
                            ("local_pickup", "Local Gallery / Store Pickup"),
                        ],
                        default="flat_rate",
                        max_length=30,
                        verbose_name="Calculation Method",
                    ),
                ),
                (
                    "flat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Flat Rate Base Amount (NPR)",
                    ),
                ),
                (
                    "min_order_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Minimum Order Subtotal",
                    ),
                ),
                (
                    "max_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Maximum Package Weight (kg)",
                    ),
                ),
                (
                    "estimated_delivery_days_min",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Est. Min Delivery Days"
                    ),
                ),
                (
                    "estimated_delivery_days_max",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Est. Max Delivery Days"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Position"
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_methods",
                        to="shipping.shippingzone",
                        verbose_name="Geographic Shipping Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Method",
                "verbose_name_plural": "Shipping Methods",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="WeightTierRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "min_weight_kg",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Min Weight Bracket (kg)",
                    ),
                ),
                (
                    "max_weight_kg",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Max Weight Bracket (kg)",
                    ),
                ),
                (
                    "rate_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Tier Delivery Fee (NPR)",
                    ),
                ),
                (
                    "shipping_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_tiers",
                        to="shipping.shippingmethod",
                        verbose_name="Shipping Method",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weight Bracket Rate",
                "verbose_name_plural": "Weight Bracket Rates",
                "ordering": ["min_weight_kg"],
            },
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=models.Index(
                fields=["code", "is_active"], name="shipping_sh_code_8a459a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=models.Index(
                fields=["zone", "is_active"], name="shipping_sh_zone_id_c68dcb_idx"
            ),
        ),
    ]
