# Generated by Django 5.1.4 on 2026-07-31 19:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethod",
            name="flat_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Flat Rate Base Amount (US$)",
            ),
        ),
        migrations.AlterField(
            model_name="shippingsettings",
            name="default_fallback_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Applied if no matching zone or shipping method is configured.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Fallback Delivery Rate (US$)",
            ),
        ),
        migrations.AlterField(
            model_name="shippingsettings",
            name="free_shipping_subtotal_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cart subtotal amount at which standard shipping becomes free storewide.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Global Free Shipping Threshold (US$)",
            ),
        ),
        migrations.AlterField(
            model_name="weighttierrate",
            name="rate_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Tier Delivery Fee (US$)",
            ),
        ),
    ]
