# Generated by Django 5.1.4 on 2026-07-23 15:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enable_tax_calculation",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle to enable or bypass all dynamic tax calculations.",
                        verbose_name="Enable Tax System System-Wide",
                    ),
                ),
                (
                    "default_calculation_mode",
                    models.CharField(
                        choices=[
                            (
                                "exclusive",
                                "Tax-Exclusive (Tax added on top of item price at checkout)",
                            ),
                            (
                                "inclusive",
                                "Tax-Inclusive (Item display price already includes tax)",
                            ),
                        ],
                        default="exclusive",
                        max_length=20,
                        verbose_name="Default Tax Calculation Mode",
                    ),
                ),
                (
                    "fallback_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("13.00"),
                        help_text="Applied when no specific regional or product tax rule matches (e.g. 13.00 for Nepal VAT).",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Fallback Global Tax Rate (%)",
                    ),
                ),
                (
                    "apply_tax_to_shipping",
                    models.BooleanField(
                        default=False,
                        help_text="Check if delivery charges should be subject to tax.",
                        verbose_name="Apply Tax to Shipping Fees",
                    ),
                ),
                (
                    "prices_include_tax_in_catalog",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, product catalog prices are treated as already including tax.",
                        verbose_name="Display Store Prices as Tax-Inclusive",
                    ),
                ),
                (
                    "round_tax_at_subtotal_level",
                    models.BooleanField(
                        default=True,
                        help_text="If false, line-item taxes are rounded individually before summing.",
                        verbose_name="Round Tax at Grand Total Level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Engine Settings",
                "verbose_name_plural": "Tax Engine Settings",
            },
        ),
        migrations.CreateModel(
            name="CustomerTaxExemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exemption_number",
                    models.CharField(
                        max_length=100, verbose_name="Tax Exemption / VAT ID Number"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Wholesale Reseller, Export Entity, Non-Profit.",
                        max_length=200,
                        null=True,
                        verbose_name="Reason / Category",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Is Verified by Admin",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Exemption Expiration Date"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_exemptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Tax Exemption",
                "verbose_name_plural": "Customer Tax Exemptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable title (e.g., 'Standard Handicraft VAT', 'Tax Exempt').",
                        max_length=100,
                        verbose_name="Tax Class Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier code (e.g. STANDARD, EXEMPT, LUXURY, SERVICE). Auto-uppercased.",
                        max_length=50,
                        unique=True,
                        verbose_name="Tax Class Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Description / Tax Regulations",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Used for catalog items when no specific tax class is assigned.",
                        verbose_name="Is Default Tax Class",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Class",
                "verbose_name_plural": "Tax Classes",
                "ordering": ["-is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="tax_taxclas_code_f40446_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Title for this geographic tax zone (e.g., 'Nepal Bagmati', 'USA California').",
                        max_length=120,
                        verbose_name="Tax Zone Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code (e.g. ZONE_NP, ZONE_US_CA, ZONE_EU). Auto-uppercased.",
                        max_length=50,
                        unique=True,
                        verbose_name="Zone Code",
                    ),
                ),
                (
                    "countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ISO country codes (e.g. ['NP', 'US', 'DE', 'FR']). Empty applies globally.",
                        verbose_name="Country Codes List (ISO 2-letter)",
                    ),
                ),
                (
                    "states_or_provinces",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of state codes or province names (e.g. ['Bagmati', 'CA', 'NY']).",
                        verbose_name="States / Provinces List",
                    ),
                ),
                (
                    "postal_code_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Wildcard or prefix matching for zip codes (e.g., '446*' or '90001-90099').",
                        max_length=100,
                        null=True,
                        verbose_name="Postal Code Pattern / Wildcard",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Lower numbers take higher precedence during location matching.",
                        verbose_name="Matching Priority",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Zone",
                "verbose_name_plural": "Tax Zones",
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="tax_taxzone_code_ff4054_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="tax_taxzone_priorit_a88f28_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Title shown on customer invoices (e.g., 'Nepal VAT 13%', 'Local Craft Surcharge 5%').",
                        max_length=150,
                        verbose_name="Tax Rule Title",
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("vat", "Value Added Tax (VAT)"),
                            ("gst", "Goods & Services Tax (GST)"),
                            ("sales_tax", "State / Regional Sales Tax"),
                            ("service_tax", "Service Charge / Tax"),
                            ("surcharge", "Additional Surcharge / Luxury Tax"),
                            ("exempt", "Tax-Exempt / Zero-Rated"),
                        ],
                        default="vat",
                        max_length=30,
                        verbose_name="Tax Type",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Rate (%)"),
                            ("flat_amount", "Flat Fixed Fee Per Item"),
                        ],
                        default="percentage",
                        max_length=20,
                        verbose_name="Rate Type",
                    ),
                ),
                (
                    "rate_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Percentage (e.g., 13.00 for 13% or 5.00 for 5%) or flat currency value.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Tax Rate Value",
                    ),
                ),
                (
                    "is_compound",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this tax is calculated on top of prior applicable tax line amounts.",
                        verbose_name="Is Compound Tax",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Lower priority numbers execute first before compound calculations.",
                        verbose_name="Execution Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "tax_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_rules",
                        to="tax.taxclass",
                        verbose_name="Product Tax Class",
                    ),
                ),
                (
                    "tax_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_rules",
                        to="tax.taxzone",
                        verbose_name="Geographic Tax Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Rule",
                "verbose_name_plural": "Tax Rules",
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["tax_class", "tax_zone", "is_active"],
                        name="tax_taxrule_tax_cla_0214ad_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="tax_taxrule_priorit_4e6cd8_idx"
                    ),
                ],
            },
        ),
    ]
