# Generated by Django 5.1.4 on 2026-07-23 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        verbose_name="Security Event Type",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="Source IP Address"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Event Parameters & Headers",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Resolved by Administrator",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Target User Account (if any)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Event Log",
                "verbose_name_plural": "Security Event Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Record Created"),
                            ("update", "Record Updated"),
                            ("delete", "Record Deleted"),
                            ("login", "User Sign-In"),
                            ("logout", "User Sign-Out"),
                            ("failed_login", "Failed Sign-In Attempt"),
                            ("password_change", "Password Reset / Change"),
                            ("checkout", "Order Checkout Processed"),
                            ("refund", "Refund Processed"),
                            ("inventory_mutation", "Inventory Adjusted"),
                        ],
                        db_index=True,
                        default="update",
                        max_length=50,
                        verbose_name="Action Performed",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning / Alert"),
                            ("security", "Security Event"),
                            ("critical", "Critical System Event"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                        verbose_name="Event Severity",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="Target Object Primary Key",
                    ),
                ),
                (
                    "target_repr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Target String Representation",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON dict mapping field names to {'old': val, 'new': val}.",
                        verbose_name="Field Diffs / Change Snapshot",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Client IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, null=True, verbose_name="Client User Agent"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Audit Timestamp",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor / User",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Target Content Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Record",
                "verbose_name_plural": "Audit Log Records",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="audit_audit_action_e33994_idx",
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"],
                        name="audit_audit_severit_34f2e8_idx",
                    ),
                    models.Index(
                        fields=["actor", "-timestamp"],
                        name="audit_audit_actor_i_dcd783_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_audit_content_4c2ead_idx",
                    ),
                ],
            },
        ),
    ]
