# Generated by Django 5.1.4 on 2026-07-16 05:46

import apps.catalog.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_items_per_page",
                    models.PositiveIntegerField(
                        blank=True,
                        default=12,
                        help_text="Number of products shown per page in the category listing view.",
                        null=True,
                        verbose_name="Default Items Per Page",
                    ),
                ),
                (
                    "price_filter_min",
                    models.PositiveIntegerField(
                        blank=True,
                        default=500,
                        help_text="Minimum range boundary for the price filter slider.",
                        null=True,
                        verbose_name="Price Filter Minimum (NPR)",
                    ),
                ),
                (
                    "price_filter_max",
                    models.PositiveIntegerField(
                        blank=True,
                        default=100000,
                        help_text="Maximum range boundary for the price filter slider.",
                        null=True,
                        verbose_name="Price Filter Maximum (NPR)",
                    ),
                ),
                (
                    "show_stock_warning_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        default=5,
                        help_text="Configured at the catalog level for UI hints; the Inventory app remains the source of truth for actual stock state.",
                        null=True,
                        verbose_name="Stock Warning Threshold",
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        blank=True,
                        default="NPR",
                        help_text="ISO 4217 currency code used as the default for new products.",
                        max_length=10,
                        null=True,
                        verbose_name="Default Currency",
                    ),
                ),
                (
                    "default_weight_unit",
                    models.CharField(
                        blank=True,
                        default="kg",
                        help_text="Unit of measurement used for product weight fields.",
                        max_length=10,
                        null=True,
                        verbose_name="Default Weight Unit",
                    ),
                ),
                (
                    "default_dimension_unit",
                    models.CharField(
                        blank=True,
                        default="cm",
                        help_text="Unit of measurement used for product dimension fields.",
                        max_length=10,
                        null=True,
                        verbose_name="Default Dimension Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Settings",
                "verbose_name_plural": "Catalog Settings",
                "db_table": "catalog_settings",
            },
        ),
        migrations.CreateModel(
            name="ProductCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Collection Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Collection Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=True,
                        null=True,
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Is Featured"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        null=True,
                        verbose_name="Sort Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Collection",
                "verbose_name_plural": "Product Collections",
                "db_table": "catalog_product_collection",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Question"
                    ),
                ),
                (
                    "answer",
                    models.TextField(blank=True, null=True, verbose_name="Answer"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        null=True,
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=True,
                        null=True,
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product FAQ",
                "verbose_name_plural": "Product FAQs",
                "db_table": "catalog_product_faq",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Gallery Image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Alt Text"
                    ),
                ),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="Caption"),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True,
                        default="image",
                        help_text="image, video, 360, etc.",
                        max_length=20,
                        null=True,
                        verbose_name="Media Type",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        null=True,
                        verbose_name="Sort Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Product Gallery",
                "verbose_name_plural": "Additional Product Galleries",
                "db_table": "catalog_product_gallery_image",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Highlight Name",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="e.g., fas fa-leaf",
                        max_length=100,
                        null=True,
                        verbose_name="Icon Class",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        null=True,
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Highlight",
                "verbose_name_plural": "Product Highlights",
                "db_table": "catalog_product_highlight",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Icon Name",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="e.g., fas fa-star",
                        max_length=100,
                        null=True,
                        verbose_name="Icon Class",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Icon Image",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        null=True,
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Icon",
                "verbose_name_plural": "Product Icons",
                "db_table": "catalog_product_icon",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Gallery Image",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Image Title",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Alt Text"
                    ),
                ),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="Caption"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Is Primary Display Image",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Display Position",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Gallery Image",
                "verbose_name_plural": "Product Gallery Images",
                "db_table": "catalog_product_image",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Label Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True,
                        default="#FFFFFF",
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex code (e.g. #FFFFFF or #FFF).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                        verbose_name="Text Color",
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        blank=True,
                        default="#2C2520",
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex code (e.g. #FFFFFF or #FFF).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                        verbose_name="Background Color",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        null=True,
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Label",
                "verbose_name_plural": "Product Labels",
                "db_table": "catalog_product_label",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schema_type",
                    models.CharField(
                        blank=True,
                        default="Product",
                        max_length=100,
                        null=True,
                        verbose_name="Schema Type",
                    ),
                ),
                (
                    "schema_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Schema JSON Data",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Schema",
                "verbose_name_plural": "Product Schemas",
                "db_table": "catalog_product_schema",
            },
        ),
        migrations.CreateModel(
            name="ProductSEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Meta Description"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keywords"
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Robots Directives",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Open Graph Title",
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Open Graph Description"
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Open Graph Image",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Twitter Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product SEO Profile",
                "verbose_name_plural": "Product SEO Profiles",
                "db_table": "catalog_product_seo",
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Specification Label",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Specification Value",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        help_text="Optional grouping (e.g. 'Materials', 'Dimensions').",
                        max_length=100,
                        null=True,
                        verbose_name="Group",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        null=True,
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Specification",
                "verbose_name_plural": "Product Specifications",
                "db_table": "catalog_product_specification",
                "ordering": ["display_order", "group", "label"],
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Tag Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=True,
                        null=True,
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Tag",
                "verbose_name_plural": "Product Tags",
                "db_table": "catalog_product_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated from attribute values, or set explicitly.",
                        max_length=255,
                        null=True,
                        verbose_name="Variant Name",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Variant-level SKU. The Inventory app references variants by this identifier.",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="UPC, EAN, ISBN, or other barcode identifier.",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Barcode",
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional. When set, replaces the parent product price.",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Price Override",
                    ),
                ),
                (
                    "compare_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional. Strikethrough price for sale display.",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Compare At Price",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional. Overrides the parent product weight.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Weight Override",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Length Override",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Width Override",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Height Override",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional. Overrides the product image when this variant is selected.",
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Variant Image",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON object describing the variant attributes (e.g. {"size": "M", "color": "red"}).',
                        verbose_name="Attributes",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex code (e.g. #FFFFFF or #FFF).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                        verbose_name="Color Hex Code",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=True,
                        null=True,
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=False,
                        help_text="Marks the default variant shown when a product page loads.",
                        null=True,
                        verbose_name="Is Default Variant",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        null=True,
                        verbose_name="Sort Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "db_table": "catalog_product_variant",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Video Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Video URL"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Video Thumbnail",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duration (seconds)"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        null=True,
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Video",
                "verbose_name_plural": "Product Videos",
                "db_table": "catalog_product_video",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RecentlyViewedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="User ID"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="Session Key",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Viewed At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recently Viewed Product",
                "verbose_name_plural": "Recently Viewed Products",
                "db_table": "catalog_recently_viewed_product",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Tag Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "catalog_tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TrustBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Badge Name",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Badge Image",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        null=True,
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Badge",
                "verbose_name_plural": "Trust Badges",
                "db_table": "catalog_trust_badge",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="VariantOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Small, Red",
                        max_length=50,
                        null=True,
                        verbose_name="Option Value",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Optional. Used for color-style variant options.",
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex code (e.g. #FFFFFF or #FFF).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                        verbose_name="Color Hex Code",
                    ),
                ),
                (
                    "swatch_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Swatch Image",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        null=True,
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant Option",
                "verbose_name_plural": "Variant Options",
                "db_table": "catalog_variant_option",
                "ordering": ["variant_type__name", "display_order", "value"],
            },
        ),
        migrations.CreateModel(
            name="VariantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Size, Color",
                        max_length=50,
                        null=True,
                        verbose_name="Variant Type",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        null=True,
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant Type",
                "verbose_name_plural": "Variant Types",
                "db_table": "catalog_variant_type",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Artisan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Artisan Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, null=True, verbose_name="Biography / Story"
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        blank=True, null=True, verbose_name="Highlight Quote"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Artisan Image",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Bhaktapur Prov., Patan Valley",
                        max_length=100,
                        null=True,
                        verbose_name="Origin Region/Province",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Website URL",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Display Position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artisan",
                "verbose_name_plural": "Artisans",
                "db_table": "catalog_artisan",
                "ordering": ["position", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="catalog_art_slug_d84dbb_idx"),
                    models.Index(
                        fields=["is_active", "position"],
                        name="catalog_art_is_acti_490d27_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("slug__isnull", False)),
                        fields=("slug",),
                        name="catalog_artisan_unique_slug_when_set",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier. Auto-generated from name if blank.",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Category Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Category Image",
                    ),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Show on Homepage",
                    ),
                ),
                (
                    "show_in_menu",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Show in Menu"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Sort Order"
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank if this is a top-level category.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="catalog.category",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "catalog_category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Collection Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "db_table": "catalog_collection",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="catalog_col_slug_d63228_idx"),
                    models.Index(
                        fields=["is_active"], name="catalog_col_is_acti_8cce0f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("slug__isnull", False)),
                        fields=("slug",),
                        name="catalog_collection_unique_slug_when_set",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EthicalStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 100% Certified Fair Trade, Eco-Friendly Sourced Wood",
                        max_length=120,
                        null=True,
                        unique=True,
                        verbose_name="Ethical Standard",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="e.g. fas fa-leaf",
                        max_length=100,
                        null=True,
                        verbose_name="Icon Class",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ethical Standard",
                "verbose_name_plural": "Ethical Standards",
                "db_table": "catalog_ethical_standard",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="catalog_eth_name_576816_idx"),
                    models.Index(
                        fields=["is_active"], name="catalog_eth_is_acti_8fa681_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Hue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Deep Mahogany, Gold Leaf",
                        max_length=100,
                        null=True,
                        verbose_name="Hue Name",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="e.g. #4E2A14",
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex code (e.g. #FFFFFF or #FFF).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                        verbose_name="Color Hex Code",
                    ),
                ),
                (
                    "swatch_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional swatch override when hex is insufficient.",
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Swatch Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hue Aesthetic",
                "verbose_name_plural": "Hue Aesthetics",
                "db_table": "catalog_hue",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="catalog_hue_name_ca00ff_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Material Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materials",
                "db_table": "catalog_material",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="catalog_mat_name_bf21dd_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Product Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stock Keeping Unit. The Inventory app references products by this identifier.",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="UPC, EAN, ISBN, or other barcode identifier.",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Barcode",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("physical", "Physical Product"),
                            ("digital", "Digital Product"),
                            ("service", "Service"),
                            ("bundle", "Bundle"),
                            ("gift_card", "Gift Card"),
                            ("subscription", "Subscription"),
                        ],
                        default="physical",
                        max_length=24,
                        null=True,
                        verbose_name="Product Type",
                    ),
                ),
                (
                    "model_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Model Number",
                    ),
                ),
                (
                    "internal_reference",
                    models.CharField(
                        blank=True,
                        help_text="Internal SKU / catalog reference, not customer-facing.",
                        max_length=100,
                        null=True,
                        verbose_name="Internal Reference",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        help_text="Displayed in lists and catalogs.",
                        null=True,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Full Description"
                    ),
                ),
                (
                    "story",
                    models.TextField(
                        blank=True,
                        help_text="Legacy narratives and storyboards.",
                        null=True,
                        verbose_name="Artisan / Product Story",
                    ),
                ),
                (
                    "crafting_process",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of how this masterpiece is crafted.",
                        null=True,
                        verbose_name="Crafting Process",
                    ),
                ),
                (
                    "care_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Detailed care steps to preserve heritage materials.",
                        null=True,
                        verbose_name="Care Instructions",
                    ),
                ),
                (
                    "shipping_information",
                    models.TextField(
                        blank=True, null=True, verbose_name="Shipping Information"
                    ),
                ),
                (
                    "delivery_promise",
                    models.TextField(
                        blank=True, null=True, verbose_name="Delivery Promise"
                    ),
                ),
                (
                    "return_policy",
                    models.TextField(
                        blank=True, null=True, verbose_name="Return Policy"
                    ),
                ),
                (
                    "warranty_information",
                    models.TextField(
                        blank=True, null=True, verbose_name="Warranty Information"
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Country of Origin",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Current Price (NPR)",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional. Populate to trigger sale pricing and line-through original price.",
                        max_digits=12,
                        null=True,
                        verbose_name="Original Price (NPR)",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Internal cost basis. Used by financial integrations.",
                        max_digits=12,
                        null=True,
                        verbose_name="Cost Price (NPR)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default="NPR",
                        help_text="ISO 4217 currency code for the pricing fields.",
                        max_length=10,
                        null=True,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "tax_class",
                    models.CharField(
                        blank=True,
                        help_text="CMS-driven tax classification reference.",
                        max_length=100,
                        null=True,
                        verbose_name="Tax Class",
                    ),
                ),
                (
                    "primary_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Primary Image",
                    ),
                ),
                (
                    "hover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Hover Image",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Primary Video URL",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Length in cm",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Length",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Width in cm",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Width",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in cm",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Height",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Weight",
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Hand Carved, Limited Edition",
                        max_length=60,
                        null=True,
                        verbose_name="Primary Badge Text",
                    ),
                ),
                (
                    "secondary_badge_text",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Traditional, Bestseller",
                        max_length=60,
                        null=True,
                        verbose_name="Secondary Badge Text",
                    ),
                ),
                (
                    "ribbon_text",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Sale, New Arrival",
                        max_length=50,
                        null=True,
                        verbose_name="Ribbon Text",
                    ),
                ),
                (
                    "ribbon_bg_color",
                    models.CharField(
                        blank=True,
                        default="#C5A880",
                        help_text="Hex color code, e.g. #C5A880",
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex code (e.g. #FFFFFF or #FFF).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                        verbose_name="Ribbon Background Color",
                    ),
                ),
                (
                    "ribbon_text_color",
                    models.CharField(
                        blank=True,
                        default="#FFFFFF",
                        help_text="Hex color code, e.g. #FFFFFF",
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex code (e.g. #FFFFFF or #FFF).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                        verbose_name="Ribbon Text Color",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                        help_text="Denormalized star rating displayed on product pages.",
                        null=True,
                        verbose_name="Rating (1-5)",
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Denormalized count displayed on product pages.",
                        null=True,
                        verbose_name="Reviews Count",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        help_text="Denormalized count of how many times this product was viewed. This is product analytics only - it is independent of inventory.",
                        null=True,
                        verbose_name="View Count",
                    ),
                ),
                (
                    "wishlist_count",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=0,
                        help_text="Denormalized count of how many users have favorited/wishlisted this product. Independent of inventory.",
                        null=True,
                        verbose_name="Wishlist Count",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        null=True,
                        verbose_name="Product Status",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        blank=True,
                        db_index=True,
                        default=False,
                        null=True,
                        verbose_name="Is Featured",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Display Position",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published At"
                    ),
                ),
                (
                    "publish_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publish From"
                    ),
                ),
                (
                    "publish_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publish Until"
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEO Keywords",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Meta Description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "robots_directives",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Robots Directives",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Open Graph Title",
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Open Graph Description"
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Open Graph Image",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Twitter Image",
                    ),
                ),
                (
                    "structured_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Schema.org Structured Data",
                    ),
                ),
                (
                    "artisan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.artisan",
                        verbose_name="Master Craftsman",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Masterpiece",
                "verbose_name_plural": "Product Masterpieces",
                "db_table": "catalog_product",
                "ordering": ["position", "-created_at"],
            },
        ),
    ]
