# Generated by Django 5.1.4 on 2026-06-27 11:21

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artisan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="Artisan Name")),
                (
                    "slug",
                    models.SlugField(max_length=150, unique=True, verbose_name="Slug"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography / Story")),
                ("quote", models.TextField(blank=True, verbose_name="Highlight Quote")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Artisan Image",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Bhaktapur Prov., Patan Valley",
                        max_length=100,
                        verbose_name="Origin Region/Province",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Position"
                    ),
                ),
            ],
            options={
                "verbose_name": "Artisan",
                "verbose_name_plural": "Artisans",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="CatalogSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_items_per_page",
                    models.PositiveIntegerField(
                        default=9,
                        help_text="Number of products shown per page in the category listing view.",
                        verbose_name="Default Items Per Page",
                    ),
                ),
                (
                    "price_filter_min",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Minimum range boundary for the price filter slider.",
                        verbose_name="Price Filter Minimum (NPR)",
                    ),
                ),
                (
                    "price_filter_max",
                    models.PositiveIntegerField(
                        default=100000,
                        help_text="Maximum range boundary for the price filter slider.",
                        verbose_name="Price Filter Maximum (NPR)",
                    ),
                ),
                (
                    "show_stock_warning_threshold",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="When inventory drops below or equals this number, show 'Only X Left' status style.",
                        verbose_name="Stock Warning Threshold",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Settings",
                "verbose_name_plural": "Catalog Settings",
            },
        ),
        migrations.CreateModel(
            name="EthicalStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 100% Certified Fair Trade, Eco-Friendly Sourced Wood",
                        max_length=120,
                        unique=True,
                        verbose_name="Ethical Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ethical Standard",
                "verbose_name_plural": "Ethical Standards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Hue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Deep Mahogany, Gold Leaf",
                        max_length=100,
                        verbose_name="Hue Name",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        help_text="e.g. #4E2A14",
                        max_length=50,
                        verbose_name="Color Hex Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hue Aesthetic",
                "verbose_name_plural": "Hue Aesthetics",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Material Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materials",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Category Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=150, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Category Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Category Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Position"
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank if this is a top-level category.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="catalog.category",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Product Title"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=180, unique=True, verbose_name="Slug"),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Displayed in lists and catalogs.",
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Full Description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Current Price (NPR)",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional. Populate to trigger sale pricing and line-through original price.",
                        max_digits=12,
                        null=True,
                        verbose_name="Original Price (NPR)",
                    ),
                ),
                (
                    "primary_image",
                    models.ImageField(
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Primary Image",
                    ),
                ),
                (
                    "hover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Hover Image",
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Hand Carved, Limited Edition",
                        max_length=60,
                        verbose_name="Primary Badge Text",
                    ),
                ),
                (
                    "secondary_badge_text",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Traditional, Bestseller",
                        max_length=60,
                        verbose_name="Secondary Badge Text",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                        verbose_name="Rating (1-5)",
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Reviews Count"
                    ),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("in", "In Stock"),
                            ("low", "Low Stock"),
                            ("out", "Out of Stock"),
                        ],
                        default="in",
                        max_length=10,
                        verbose_name="Stock Status",
                    ),
                ),
                (
                    "stock_text",
                    models.CharField(
                        blank=True,
                        help_text="Optional. Custom text like 'Only 2 Left'. If blank, defaults based on status.",
                        max_length=100,
                        verbose_name="Stock Label Overwrite",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Is Featured"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Position"
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="SEO Description"
                    ),
                ),
                (
                    "artisan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.artisan",
                        verbose_name="Master Craftsman",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "ethical_standards",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="catalog.ethicalstandard",
                        verbose_name="Ethical Standards",
                    ),
                ),
                (
                    "hue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.hue",
                        verbose_name="Hue Aesthetic",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.material",
                        verbose_name="Material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Masterpiece",
                "verbose_name_plural": "Product Masterpieces",
                "ordering": ["position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Gallery Image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Alt Text"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Position"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Gallery Image",
                "verbose_name_plural": "Product Gallery Images",
                "ordering": ["position", "id"],
            },
        ),
    ]
