# Generated by Django 5.1.4 on 2026-06-29 02:51

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="position",
        ),
        migrations.AddField(
            model_name="category",
            name="show_in_menu",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Show in Menu"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="show_on_homepage",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Show on Homepage"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="sort_order",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Sort Order"
            ),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="bio",
            field=models.TextField(
                blank=True, null=True, verbose_name="Biography / Story"
            ),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Is Active"
            ),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="name",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Artisan Name"
            ),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Display Position"
            ),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="quote",
            field=models.TextField(
                blank=True, null=True, verbose_name="Highlight Quote"
            ),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="e.g. Bhaktapur Prov., Patan Valley",
                max_length=100,
                null=True,
                verbose_name="Origin Region/Province",
            ),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="default_items_per_page",
            field=models.PositiveIntegerField(
                blank=True,
                default=9,
                help_text="Number of products shown per page in the category listing view.",
                null=True,
                verbose_name="Default Items Per Page",
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="price_filter_max",
            field=models.PositiveIntegerField(
                blank=True,
                default=100000,
                help_text="Maximum range boundary for the price filter slider.",
                null=True,
                verbose_name="Price Filter Maximum (NPR)",
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="price_filter_min",
            field=models.PositiveIntegerField(
                blank=True,
                default=500,
                help_text="Minimum range boundary for the price filter slider.",
                null=True,
                verbose_name="Price Filter Minimum (NPR)",
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="show_stock_warning_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                default=5,
                help_text="When inventory drops below or equals this number, show 'Only X Left' status style.",
                null=True,
                verbose_name="Stock Warning Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Category Description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Is Active"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Category Name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="ethicalstandard",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="e.g. 100% Certified Fair Trade, Eco-Friendly Sourced Wood",
                max_length=120,
                null=True,
                unique=True,
                verbose_name="Ethical Standard",
            ),
        ),
        migrations.AlterField(
            model_name="hue",
            name="color_code",
            field=models.CharField(
                blank=True,
                help_text="e.g. #4E2A14",
                max_length=50,
                null=True,
                verbose_name="Color Hex Code",
            ),
        ),
        migrations.AlterField(
            model_name="hue",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="e.g. Deep Mahogany, Gold Leaf",
                max_length=100,
                null=True,
                verbose_name="Hue Name",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Material Name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="artisan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.artisan",
                verbose_name="Master Craftsman",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="badge_text",
            field=models.CharField(
                blank=True,
                help_text="e.g. Hand Carved, Limited Edition",
                max_length=60,
                null=True,
                verbose_name="Primary Badge Text",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Full Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Is Active"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Is Featured"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Display Position"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Current Price (NPR)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="primary_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.models._upload_to_catalog_media,
                verbose_name="Primary Image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=5,
                null=True,
                verbose_name="Rating (1-5)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="reviews_count",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Reviews Count"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="secondary_badge_text",
            field=models.CharField(
                blank=True,
                help_text="e.g. Traditional, Bestseller",
                max_length=60,
                null=True,
                verbose_name="Secondary Badge Text",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="Displayed in lists and catalogs.",
                null=True,
                verbose_name="Short Description",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=180, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in", "In Stock"),
                    ("low", "Low Stock"),
                    ("out", "Out of Stock"),
                ],
                default="in",
                max_length=10,
                null=True,
                verbose_name="Stock Status",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_text",
            field=models.CharField(
                blank=True,
                help_text="Optional. Custom text like 'Only 2 Left'. If blank, defaults based on status.",
                max_length=100,
                null=True,
                verbose_name="Stock Label Overwrite",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Product Title"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Alt Text"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.models._upload_to_catalog_media,
                verbose_name="Gallery Image",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="position",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Display Position"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
    ]
