# Generated by Django 5.1.4 on 2026-07-16 05:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                help_text="AUDIT-ONLY traceability link to the cart line item that produced this product's cart snapshot. The Order app remains the single source of truth for cart state.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="catalog_product_line_items",
                to="orders.orderitem",
                verbose_name="Order Line Item (Audit Reference)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.category",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cross_sell_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="cross_sold_by",
                to="catalog.product",
                verbose_name="Cross Sell Products",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ethical_standards",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.ethicalstandard",
                verbose_name="Ethical Standards",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.hue",
                verbose_name="Hue Aesthetic",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.material",
                verbose_name="Material",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_to",
                to="catalog.product",
                verbose_name="Related Products",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="upsell_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="upsold_by",
                to="catalog.product",
                verbose_name="Upsell Products",
            ),
        ),
        migrations.AddField(
            model_name="productcollection",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="in_collections",
                to="catalog.product",
                verbose_name="Collection Products",
            ),
        ),
        migrations.AddField(
            model_name="productfaq",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faqs",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_galleries",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddIndex(
            model_name="producthighlight",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="catalog_pro_is_acti_a90a51_idx",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="highlights",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.producthighlight",
                verbose_name="Product Highlights",
            ),
        ),
        migrations.AddIndex(
            model_name="producticon",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="catalog_pro_is_acti_447685_idx",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="icons",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.producticon",
                verbose_name="Product Icons",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddIndex(
            model_name="productlabel",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="catalog_pro_is_acti_216fcb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productlabel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug__isnull", False)),
                fields=("slug",),
                name="catalog_product_label_unique_slug_when_set",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.productlabel",
                verbose_name="Product Labels",
            ),
        ),
        migrations.AddField(
            model_name="productschema",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schema_config",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productseo",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seo_config",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="producttag",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="tags",
                to="catalog.product",
                verbose_name="Tagged Products",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                help_text="AUDIT-ONLY traceability link to the cart line item that produced this variant's cart snapshot. The Order app remains the single source of truth for cart state.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="catalog_variant_line_items",
                to="orders.orderitem",
                verbose_name="Order Line Item (Audit Reference)",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productvideo",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="recentlyviewedproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recently_viewed",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["slug"], name="catalog_tag_slug_676fab_idx"),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug__isnull", False)),
                fields=("slug",),
                name="catalog_tag_unique_slug_when_set",
            ),
        ),
        migrations.AddIndex(
            model_name="trustbadge",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="catalog_tru_is_acti_facbca_idx",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="trust_badges",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.trustbadge",
                verbose_name="Trust Badges",
            ),
        ),
        migrations.AddIndex(
            model_name="varianttype",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="catalog_var_is_acti_8a69fb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="varianttype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name__isnull", False)),
                fields=("name",),
                name="catalog_variant_type_unique_name_when_set",
            ),
        ),
        migrations.AddField(
            model_name="variantoption",
            name="variant_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="catalog.varianttype",
                verbose_name="Variant Type",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="catalog_cat_slug_695af4_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "is_active"], name="catalog_cat_parent__e2d7e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "show_in_menu"],
                name="catalog_cat_is_acti_6aae28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "show_on_homepage"],
                name="catalog_cat_is_acti_d7949a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug__isnull", False)),
                fields=("slug",),
                name="catalog_category_unique_slug_when_set",
            ),
        ),
        migrations.AddIndex(
            model_name="productcollection",
            index=models.Index(fields=["slug"], name="catalog_pro_slug_ea815c_idx"),
        ),
        migrations.AddIndex(
            model_name="productcollection",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="catalog_pro_is_acti_1c8906_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productcollection",
            index=models.Index(
                fields=["is_featured"], name="catalog_pro_is_feat_15b09e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productcollection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug__isnull", False)),
                fields=("slug",),
                name="catalog_product_collection_unique_slug_when_set",
            ),
        ),
        migrations.AddIndex(
            model_name="productfaq",
            index=models.Index(
                fields=["product", "is_active"], name="catalog_pro_product_3fe09b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productgalleryimage",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_pro_product_4eeae7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "position"], name="catalog_pro_product_643608_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_primary"], name="catalog_pro_product_b85580_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productspecification",
            index=models.Index(
                fields=["product", "display_order"],
                name="catalog_pro_product_4cc698_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productspecification",
            index=models.Index(
                fields=["product", "group"], name="catalog_pro_product_218c01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producttag",
            index=models.Index(fields=["slug"], name="catalog_pro_slug_14b751_idx"),
        ),
        migrations.AddIndex(
            model_name="producttag",
            index=models.Index(
                fields=["is_active"], name="catalog_pro_is_acti_90cc31_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug__isnull", False)),
                fields=("slug",),
                name="catalog_product_tag_unique_slug_when_set",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "is_active"], name="catalog_pro_product_5fcf5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "is_default"], name="catalog_pro_product_4ac882_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "sort_order"], name="catalog_pro_product_b56316_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku__isnull", False)),
                fields=("sku",),
                name="catalog_variant_unique_sku_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode__isnull", False)),
                fields=("barcode",),
                name="catalog_variant_unique_barcode_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price_override__isnull", True),
                    ("price_override__gte", Decimal("0")),
                    _connector="OR",
                ),
                name="catalog_variant_price_override_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("compare_price__isnull", True),
                    ("compare_price__gte", Decimal("0")),
                    _connector="OR",
                ),
                name="catalog_variant_compare_price_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price_override__isnull", True),
                    ("compare_price__isnull", True),
                    ("compare_price__gte", models.F("price_override")),
                    _connector="OR",
                ),
                name="catalog_variant_compare_gte_override",
            ),
        ),
        migrations.AddIndex(
            model_name="productvideo",
            index=models.Index(
                fields=["product", "is_active"], name="catalog_pro_product_18984a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recentlyviewedproduct",
            index=models.Index(
                fields=["session_key", "-viewed_at"],
                name="catalog_rec_session_168ad8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recentlyviewedproduct",
            index=models.Index(
                fields=["user_id", "-viewed_at"], name="catalog_rec_user_id_25456e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recentlyviewedproduct",
            index=models.Index(
                fields=["product", "-viewed_at"], name="catalog_rec_product_330151_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_active"], name="catalog_pro_status_5592a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="catalog_pro_sku_2c4c34_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["barcode"], name="catalog_pro_barcode_58f8f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-wishlist_count"], name="catalog_pro_wishlis_811ada_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-view_count"], name="catalog_pro_view_co_c5555c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="catalog_pro_slug_2b1eb6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="catalog_pro_categor_da0f0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["artisan", "status"], name="catalog_pro_artisan_d12129_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_featured"], name="catalog_pro_status_70303b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["position"], name="catalog_pro_positio_417d20_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku__isnull", False)),
                fields=("sku",),
                name="catalog_product_unique_sku_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode__isnull", False)),
                fields=("barcode",),
                name="catalog_product_unique_barcode_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug__isnull", False)),
                fields=("slug",),
                name="catalog_product_unique_slug_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("internal_reference__isnull", False)),
                fields=("internal_reference",),
                name="catalog_product_unique_internal_ref_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("original_price__isnull", True),
                    ("price__isnull", True),
                    ("original_price__gt", models.F("price")),
                    _connector="OR",
                ),
                name="catalog_product_original_price_gt_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating__isnull", True),
                    models.Q(("rating__gte", 1), ("rating__lte", 5)),
                    _connector="OR",
                ),
                name="catalog_product_rating_in_range",
            ),
        ),
        migrations.AddIndex(
            model_name="variantoption",
            index=models.Index(
                fields=["variant_type", "is_active"],
                name="catalog_var_variant_7240e9_idx",
            ),
        ),
    ]
