# Generated by Django 5.1.4 on 2026-06-29 07:11

import apps.catalog.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options_remove_category_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Collection Name"),
                ),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Collection Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=150, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Collection Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
            ],
            options={
                "verbose_name": "Product Collection",
                "verbose_name_plural": "Product Collections",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Gallery Image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Alt Text"
                    ),
                ),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="Caption"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
            ],
            options={
                "verbose_name": "Additional Product Gallery",
                "verbose_name_plural": "Additional Product Galleries",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schema_type",
                    models.CharField(
                        default="Product", max_length=100, verbose_name="Schema Type"
                    ),
                ),
                (
                    "schema_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Schema JSON Data"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Product Schema",
                "verbose_name_plural": "Product Schemas",
            },
        ),
        migrations.CreateModel(
            name="ProductSEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Meta Description"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keywords"
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Canonical URL"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Robots Directives",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Open Graph Title",
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Open Graph Description"
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Open Graph Image",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Twitter Title",
                    ),
                ),
                (
                    "twitter_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Twitter Description"
                    ),
                ),
                (
                    "twitter_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Twitter Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product SEO Profile",
                "verbose_name_plural": "Product SEO Profiles",
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tag Name"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Tag",
                "verbose_name_plural": "Product Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Variant Name")),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Barcode",
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Price Override",
                    ),
                ),
                (
                    "compare_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Compare At Price",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stock Quantity"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Sort Order"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VariantOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.CharField(
                        help_text="e.g., Small, Red",
                        max_length=50,
                        verbose_name="Option Value",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant Option",
                "verbose_name_plural": "Variant Options",
                "ordering": ["variant_type__name", "value"],
            },
        ),
        migrations.CreateModel(
            name="VariantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Size, Color",
                        max_length=50,
                        verbose_name="Variant Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant Type",
                "verbose_name_plural": "Variant Types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Barcode",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="canonical_url",
            field=models.URLField(blank=True, null=True, verbose_name="Canonical URL"),
        ),
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in cm",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Height",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Length in cm",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Length",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta Description"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_keywords",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Meta Keywords"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Meta Title"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="og_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Open Graph Description"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="og_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.models._upload_to_catalog_media,
                verbose_name="Open Graph Image",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="og_title",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Open Graph Title"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="publish_from",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Publish From"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="publish_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Publish Until"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Published At"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_to",
                to="catalog.product",
                verbose_name="Related Products",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="robots_directives",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Robots Directives"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="Product Status",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="structured_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="Schema.org Structured Data",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="twitter_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Twitter Description"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="twitter_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.models._upload_to_catalog_media,
                verbose_name="Twitter Image",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="twitter_title",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Twitter Title"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kg",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Weight",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width in cm",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Width",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="caption",
            field=models.TextField(blank=True, null=True, verbose_name="Caption"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_primary",
            field=models.BooleanField(
                default=False, verbose_name="Is Primary Display Image"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="title",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Image Title"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                null=True,
                verbose_name="Is Featured",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_active"], name="catalog_pro_status_5592a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="catalog_pro_sku_2c4c34_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["barcode"], name="catalog_pro_barcode_58f8f8_idx"
            ),
        ),
        migrations.AddField(
            model_name="productcollection",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="in_collections",
                to="catalog.product",
                verbose_name="Collection Products",
            ),
        ),
        migrations.AddField(
            model_name="productgalleryimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_galleries",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productschema",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schema_config",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="productseo",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seo_config",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="producttag",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="tags",
                to="catalog.product",
                verbose_name="Tagged Products",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="variantoption",
            name="variant_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="catalog.varianttype",
            ),
        ),
    ]
