# Generated by Django 5.1.4 on 2026-07-21 19:15

import apps.catalog.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artisan",
            name="region",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Origin Region/Province",
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="default_currency",
            field=models.CharField(
                blank=True,
                default="NPR",
                max_length=10,
                null=True,
                verbose_name="Default Currency",
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="default_dimension_unit",
            field=models.CharField(
                blank=True,
                default="cm",
                max_length=10,
                null=True,
                verbose_name="Default Dimension Unit",
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="default_items_per_page",
            field=models.PositiveIntegerField(
                blank=True, default=12, null=True, verbose_name="Default Items Per Page"
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="default_weight_unit",
            field=models.CharField(
                blank=True,
                default="kg",
                max_length=10,
                null=True,
                verbose_name="Default Weight Unit",
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="price_filter_max",
            field=models.PositiveIntegerField(
                blank=True,
                default=100000,
                null=True,
                verbose_name="Price Filter Maximum (NPR)",
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="price_filter_min",
            field=models.PositiveIntegerField(
                blank=True,
                default=500,
                null=True,
                verbose_name="Price Filter Minimum (NPR)",
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="show_stock_warning_threshold",
            field=models.PositiveIntegerField(
                blank=True, default=5, null=True, verbose_name="Stock Warning Threshold"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="catalog.category",
                verbose_name="Parent Category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="ethicalstandard",
            name="icon",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Icon Class"
            ),
        ),
        migrations.AlterField(
            model_name="ethicalstandard",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                unique=True,
                verbose_name="Ethical Standard",
            ),
        ),
        migrations.AlterField(
            model_name="hue",
            name="color_code",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be a valid hex code (e.g. #FFFFFF or #FFF).",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
                verbose_name="Color Hex Code",
            ),
        ),
        migrations.AlterField(
            model_name="hue",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Hue Name"
            ),
        ),
        migrations.AlterField(
            model_name="hue",
            name="swatch_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.models._upload_to_catalog_media,
                verbose_name="Swatch Image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="badge_text",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Primary Badge Text"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Barcode",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="care_instructions",
            field=models.TextField(
                blank=True, null=True, verbose_name="Care Instructions"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="catalog_product_line_items",
                to="orders.orderitem",
                verbose_name="Order Line Item (Audit Reference)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Cost Price (NPR)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="crafting_process",
            field=models.TextField(
                blank=True, null=True, verbose_name="Crafting Process"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                blank=True,
                default="NPR",
                max_length=10,
                null=True,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Height",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="internal_reference",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Internal Reference"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Length",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Original Price (NPR)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=5,
                null=True,
                verbose_name="Rating (1-5)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="reviews_count",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Reviews Count"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ribbon_bg_color",
            field=models.CharField(
                blank=True,
                default="#C5A880",
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be a valid hex code (e.g. #FFFFFF or #FFF).",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
                verbose_name="Ribbon Background Color",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ribbon_text",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ribbon Text"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ribbon_text_color",
            field=models.CharField(
                blank=True,
                default="#FFFFFF",
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be a valid hex code (e.g. #FFFFFF or #FFF).",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
                verbose_name="Ribbon Text Color",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="secondary_badge_text",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="Secondary Badge Text",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="story",
            field=models.TextField(
                blank=True, null=True, verbose_name="Artisan / Product Story"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tax_class",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tax Class"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="view_count",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                default=0,
                null=True,
                verbose_name="View Count",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Weight",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Width",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="wishlist_count",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                default=0,
                null=True,
                verbose_name="Wishlist Count",
            ),
        ),
        migrations.AlterField(
            model_name="productgalleryimage",
            name="media_type",
            field=models.CharField(
                blank=True,
                default="image",
                max_length=20,
                null=True,
                verbose_name="Media Type",
            ),
        ),
        migrations.AlterField(
            model_name="producthighlight",
            name="icon_class",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Icon Class"
            ),
        ),
        migrations.AlterField(
            model_name="producticon",
            name="icon_class",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Icon Class"
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="group",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Group"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="attributes",
            field=models.JSONField(blank=True, default=dict, verbose_name="Attributes"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Barcode",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="catalog_variant_line_items",
                to="orders.orderitem",
                verbose_name="Order Line Item (Audit Reference)",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="compare_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Compare At Price",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalog.models._upload_to_catalog_media,
                verbose_name="Variant Image",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="is_default",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                null=True,
                verbose_name="Is Default Variant",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Variant Name"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Price Override",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Weight Override",
            ),
        ),
        migrations.AlterField(
            model_name="variantoption",
            name="color_code",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be a valid hex code (e.g. #FFFFFF or #FFF).",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
                verbose_name="Color Hex Code",
            ),
        ),
        migrations.AlterField(
            model_name="variantoption",
            name="value",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Option Value"
            ),
        ),
        migrations.AlterField(
            model_name="varianttype",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Variant Type"
            ),
        ),
    ]
