# Generated by Django 5.1.4 on 2026-06-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_collection_productcollection_productgalleryimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="view_count",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                default=0,
                help_text="Denormalized count for recently viewed and trending analytics.",
                null=True,
                verbose_name="View Count",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="wishlist_count",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                default=0,
                help_text="Denormalized count of how many users have favorited/wishlisted this product.",
                null=True,
                verbose_name="Wishlist Count",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-wishlist_count"], name="catalog_pro_wishlis_811ada_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-view_count"], name="catalog_pro_view_co_c5555c_idx"
            ),
        ),
    ]
