# Generated by Django 5.1.4 on 2026-07-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_artisan_region_and_more"),
        ("orders", "0002_remove_couponusage_coupon_usage_discount_gte_0_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="catalog_pro_status_70303b_idx",
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=True,
                null=True,
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                db_index=True,
                default=5,
                null=True,
                verbose_name="Rating (1-5)",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_active", "price"],
                name="catalog_pro_status_fd8f37_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_active", "rating"],
                name="catalog_pro_status_efe06f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_active", "is_featured"],
                name="catalog_pro_status_de2947_idx",
            ),
        ),
    ]
