# Generated by Django 5.1.4 on 2026-07-01 14:26

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_view_count_product_wishlist_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Highlight Name"
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="e.g., fas fa-leaf",
                        max_length=100,
                        null=True,
                        verbose_name="Icon Class",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Highlight",
                "verbose_name_plural": "Product Highlights",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Icon Name"
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="e.g., fas fa-star",
                        max_length=100,
                        null=True,
                        verbose_name="Icon Class",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Icon Image",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Icon",
                "verbose_name_plural": "Product Icons",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Label Name"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "text_color",
                    models.CharField(
                        default="#FFFFFF", max_length=7, verbose_name="Text Color"
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        default="#2C2520", max_length=7, verbose_name="Background Color"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Label",
                "verbose_name_plural": "Product Labels",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TrustBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Badge Name"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Badge Image",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Badge",
                "verbose_name_plural": "Trust Badges",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="care_instructions",
            field=models.TextField(
                blank=True,
                help_text="Detailed care steps to preserve heritage materials.",
                null=True,
                verbose_name="Care Instructions",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="crafting_process",
            field=models.TextField(
                blank=True,
                help_text="Detailed explanation of how this masterpiece is crafted.",
                null=True,
                verbose_name="Crafting Process",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cross_sell_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="cross_sold_by",
                to="catalog.product",
                verbose_name="Cross Sell Products",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_promise",
            field=models.TextField(
                blank=True, null=True, verbose_name="Delivery Promise"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="return_policy",
            field=models.TextField(blank=True, null=True, verbose_name="Return Policy"),
        ),
        migrations.AddField(
            model_name="product",
            name="ribbon_bg_color",
            field=models.CharField(
                default="#C5A880",
                help_text="Hex color code, e.g. #C5A880",
                max_length=7,
                verbose_name="Ribbon Background Color",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ribbon_text",
            field=models.CharField(
                blank=True,
                help_text="e.g. Sale, New Arrival",
                max_length=50,
                null=True,
                verbose_name="Ribbon Text",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ribbon_text_color",
            field=models.CharField(
                default="#FFFFFF",
                help_text="Hex color code, e.g. #FFFFFF",
                max_length=7,
                verbose_name="Ribbon Text Color",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_keywords",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SEO Keywords"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_information",
            field=models.TextField(
                blank=True, null=True, verbose_name="Shipping Information"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="story",
            field=models.TextField(
                blank=True,
                help_text="Legacy narratives and storyboards.",
                null=True,
                verbose_name="Artisan / Product Story",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="upsell_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="upsold_by",
                to="catalog.product",
                verbose_name="Upsell Products",
            ),
        ),
        migrations.CreateModel(
            name="ProductFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=255, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product FAQ",
                "verbose_name_plural": "Product FAQs",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="highlights",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.producthighlight",
                verbose_name="Product Highlights",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="icons",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.producticon",
                verbose_name="Product Icons",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.productlabel",
                verbose_name="Product Labels",
            ),
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        max_length=100, verbose_name="Specification Label"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=255, verbose_name="Specification Value"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Specification",
                "verbose_name_plural": "Product Specifications",
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Video Title",
                    ),
                ),
                ("video_url", models.URLField(verbose_name="Video URL")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.catalog.models._upload_to_catalog_media,
                        verbose_name="Video Thumbnail",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Video",
                "verbose_name_plural": "Product Videos",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="trust_badges",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.trustbadge",
                verbose_name="Trust Badges",
            ),
        ),
        migrations.CreateModel(
            name="RecentlyViewedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="User ID"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                        null=True,
                        verbose_name="Session Key",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Viewed At"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recently_viewed",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recently Viewed Product",
                "verbose_name_plural": "Recently Viewed Products",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["session_key", "-viewed_at"],
                        name="catalog_rec_session_313294_idx",
                    ),
                    models.Index(
                        fields=["user_id", "-viewed_at"],
                        name="catalog_rec_user_id_9b9f66_idx",
                    ),
                ],
            },
        ),
    ]
