# Generated by Django 5.1.4 on 2026-07-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_product_catalog_pro_status_70303b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogsettings",
            name="default_currency",
            field=models.CharField(
                blank=True,
                default="USD",
                help_text="System default currency code (e.g., USD, NPR, EUR, GBP). Modifying this in CMS changes the display currency across storefront and checkout.",
                max_length=10,
                null=True,
                verbose_name="Default Currency Code",
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="price_filter_max",
            field=models.PositiveIntegerField(
                blank=True, default=5000, null=True, verbose_name="Price Filter Maximum"
            ),
        ),
        migrations.AlterField(
            model_name="catalogsettings",
            name="price_filter_min",
            field=models.PositiveIntegerField(
                blank=True, default=5, null=True, verbose_name="Price Filter Minimum"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Cost Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                blank=True,
                default="USD",
                max_length=10,
                null=True,
                verbose_name="Currency Code",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Original Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Current Price",
            ),
        ),
    ]
