# Generated by Django 5.1.4 on 2026-07-23 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Transactional Email Notifications"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=True, verbose_name="SMS Shipping Updates"
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        default=False, verbose_name="Promotional Offers & Newsletters"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Notification Preference",
                "verbose_name_plural": "Customer Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique trigger code (e.g. 'order_placed', 'shipment_dispatched', 'payment_captured').",
                        max_length=100,
                        verbose_name="Template Code",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Template Name"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email Dispatch"),
                            ("sms", "SMS Mobile Text"),
                            ("push", "Web Push Notification"),
                            ("in_app", "In-App Customer Alert"),
                        ],
                        db_index=True,
                        default="email",
                        max_length=30,
                        verbose_name="Notification Channel",
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        blank=True,
                        help_text="Supports template variables (e.g., 'Order Confirmed #{{ order_number }}').",
                        max_length=255,
                        null=True,
                        verbose_name="Subject Line Template (Email/Push)",
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="HTML/Plain text content using Django template context variables.",
                        verbose_name="Body Markup / Text Template",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["code", "channel"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "channel"),
                        name="unique_template_code_per_channel",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Recipient Address / Phone / ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email Dispatch"),
                            ("sms", "SMS Mobile Text"),
                            ("push", "Web Push Notification"),
                            ("in_app", "In-App Customer Alert"),
                        ],
                        db_index=True,
                        default="email",
                        max_length=30,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Dispatched Subject",
                    ),
                ),
                ("body", models.TextField(verbose_name="Rendered Content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued in Outbox"),
                            ("sent", "Dispatched / Sent"),
                            ("failed", "Delivery Failed"),
                            ("read", "Read by Recipient"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=30,
                        verbose_name="Delivery Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message (if failed)"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Dispatched Timestamp",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Context Data Snapshot"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient Account",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="notifications.notificationtemplate",
                        verbose_name="Source Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Audit Log",
                "verbose_name_plural": "Notification Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"],
                        name="notificatio_recipie_0ed09c_idx",
                    ),
                    models.Index(
                        fields=["channel", "status"],
                        name="notificatio_channel_f70f70_idx",
                    ),
                ],
            },
        ),
    ]
