# Generated by Django 5.1.4 on 2026-07-24 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default="Global Notification Configuration",
                        help_text="Name descriptor for this setting profile.",
                        max_length=150,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable this configuration profile globally.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("custom", "Custom SMTP"),
                            ("gmail", "Gmail"),
                            ("yahoo", "Yahoo Mail"),
                            ("outlook", "Outlook / Hotmail"),
                            ("ses", "Amazon SES SMTP"),
                        ],
                        default="custom",
                        help_text="Select a pre-configured provider or configure custom SMTP.",
                        max_length=30,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        default="smtp.gmail.com",
                        help_text="The SMTP server host.",
                        max_length=255,
                        verbose_name="SMTP Host",
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(
                        default=587,
                        help_text="Network port for connections.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                        verbose_name="SMTP Port",
                    ),
                ),
                (
                    "encryption",
                    models.CharField(
                        choices=[
                            ("tls", "STARTTLS (Explicit TLS)"),
                            ("ssl", "SSL/TLS (Implicit SSL)"),
                            ("none", "None / Unencrypted"),
                        ],
                        default="tls",
                        help_text="SSL/TLS connection scheme.",
                        max_length=20,
                        verbose_name="Encryption",
                    ),
                ),
                (
                    "auth_mode",
                    models.CharField(
                        choices=[("plain", "Plain"), ("login", "Login")],
                        default="plain",
                        help_text="SMTP authentication mechanism.",
                        max_length=20,
                        verbose_name="Auth Mode",
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Handshake username.",
                        max_length=255,
                        verbose_name="SMTP Username",
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Handshake credential/password.",
                        max_length=255,
                        verbose_name="SMTP Password",
                    ),
                ),
                (
                    "default_from_email",
                    models.EmailField(
                        default="noreply@gobindashandicrafts.com",
                        help_text="Sender envelope email address.",
                        max_length=254,
                        verbose_name="Default From Email",
                    ),
                ),
                (
                    "default_sender_name",
                    models.CharField(
                        default="Gobindas Handicrafts",
                        help_text="Sender visual name display.",
                        max_length=150,
                        verbose_name="Default Sender Name",
                    ),
                ),
                (
                    "company_notification_email",
                    models.EmailField(
                        default="admin@gobindashandicrafts.com",
                        help_text="Email address receiving user registration and administrative alerts.",
                        max_length=254,
                        verbose_name="Company Notification Email",
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Connection timeout threshold in seconds.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="Timeout",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Max sending attempts allowed for failed logs.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Max Retries",
                    ),
                ),
                (
                    "retry_delay",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Seconds to wait before scheduling another retry.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(86400),
                        ],
                        verbose_name="Retry Delay",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Setting",
                "verbose_name_plural": "Notification Settings",
            },
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Unique trigger code (e.g. 'order_placed', 'welcome_customer', 'new_user_alert_admin').",
                max_length=100,
                verbose_name="Template Code",
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="subject_template",
            field=models.CharField(
                blank=True,
                help_text="Supports template variables (e.g., 'Welcome to {{ site_title }}, {{ user.username }}').",
                max_length=255,
                null=True,
                verbose_name="Subject Line Template (Email/Push)",
            ),
        ),
    ]
